executor: docker-node
steps:
  - restore-workspace
  - run:
      name: 'Terraform Apply'
      command: yarn cli terraform --stage=prod apply
#      - run:
#          name: 'Terraform Destroy'
#          command: terraform -chdir=terraform destroy

