executor: docker-node
steps:
  - restore-infra-workspace
  - run:
      name: 'Terraform Init'
      command: pnpm run cli terraform --stage prod init
  - run:
      name: 'Terraform Apply'
      command: pnpm run cli terraform --stage prod apply
