parameters:
  resource_class:
    type: string
  max_old_space_size:
    type: integer

# Can't build with machine image, causes build issues
executor: docker-node-arm64

resource_class: << parameters.resource_class >>

environment:
  NODE_OPTIONS: --max-old-space-size=<< parameters.max_old_space_size >>
  NX_CACHE_DIRECTORY: .nx/cache-libs

steps:
  - restore-workspace
  - build-nx-libs
