executor: docker-node-neo4j
resource_class: medium
steps:
  - restore-workspace
  - run:
      name: 'Check GraphQL Codegen'
      command: pnpm cli tasks codegen --stage ci
  - run:
      name: 'Check Generate Workspace'
      command: pnpm cli tasks generate-workspace --stage ci
