parameters:
  resource_class:
    type: string

executor: docker-node-neo4j

resource_class: << parameters.resource_class >>

steps:
  - restore-workspace
  - run:
      name: 'Check GraphQL Codegen'
      command: pnpm cli tasks graphql-codegen --stage ci
  - run:
      name: 'Check Generate Workspace'
      command: pnpm cli tasks workspace-codegen --stage ci
