executor: docker-node-neo4j
resource_class: medium
steps:
  - restore-workspace
  - run:
      name: 'Install Vercel CLI'
      command: npm install --global vercel@latest
  - run:
      name: 'Pull Vercel Environment Information'
      command: vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
  - run:
      name: 'Build Project Artifacts'
      command: vercel build --token=$VERCEL_TOKEN
  - run:
      name: 'Deploy Project Artifacts to Vercel'
      command: vercel deploy --prebuilt --token=$VERCEL_TOKEN
