executor: docker-node

resource_class: large

environment:
  NODE_OPTIONS: --max-old-space-size=6144

steps:
  - restore-workspace
    # This step ensures that Docker commands run in this job will execute on a remote Docker engine.
  - setup_remote_docker:
      docker_layer_caching: true
  # https://discuss.circleci.com/t/pass-env-vars-to-docker-containers-in-circle-2-0/17827/2
  - run:
      name: 'Build landing Docker image'
      command: (./scripts/docker/prod/build-landing.sh)
  - run:
      name: 'Push Docker Image'
      command: docker compose --verbose -f .docker/prod/build.docker-compose.yaml push landing
