executor: docker-node
resource_class: large
steps:
  - restore-workspace
    # This step ensures that Docker commands run in this job will execute on a remote Docker engine.
  - setup_remote_docker:
      docker_layer_caching: true
  - run:
      name: 'Build platform api Docker image'
      command: docker compose --verbose -f .docker/prod/docker-compose.yaml build platform-api
  - run:
      name: 'Push Docker Image'
      command: docker compose --verbose -f .docker/prod/docker-compose.yaml push platform-api
