executor: docker-node-amd64

resource_class: large

environment:
  NODE_OPTIONS: --max-old-space-size=6144

steps:
  - restore-workspace
    # This step ensures that Docker commands run in this job will execute on a remote Docker engine.
  - setup_remote_docker:
      docker_layer_caching: true
  # Build for AMD64 architecture since DigitalOcean Kubernetes only supports AMD64 nodes, not ARM
  - run:
      name: 'Build and Push Sites Docker Image'
      command: docker buildx bake --file .docker/prod/base.bake.hcl --file .docker/prod/sites.bake.hcl --push --progress=plain
