executor: docker-node

resource_class: large

environment:
  NODE_OPTIONS: --max-old-space-size=6144

steps:
  - restore-workspace
    # This step ensures that Docker commands run in this job will execute on a remote Docker engine.
  - setup_remote_docker:
      docker_layer_caching: true
  # Use Makefile for building and pushing Docker images
  - run:
      name: 'Build and Push Sites Docker Image'
      command: docker buildx bake --file .docker/docker-bake.hcl --push sites
