executor: docker-node
resource_class: large
steps:
  - restore-workspace
    # This step ensures that Docker commands run in this job will execute on a remote Docker engine.
  - setup_remote_docker:
      docker_layer_caching: true
  # https://discuss.circleci.com/t/pass-env-vars-to-docker-containers-in-circle-2-0/17827/2
  - run:
      name: 'Build web Docker image'
      command: |
<<<<<<< HEAD:.circleci/config/jobs/docker-web.yml
        docker compose --verbose -f .docker/prod/build.docker-compose.yaml build web
  - run:
      name: 'Push Docker Image'
      command: docker compose --verbose -f .docker/prod/build.docker-compose.yaml push web
=======
        docker compose --verbose -f .docker/prod/build.docker-compose.yaml build platform
  - run:
      name: 'Push Docker Image'
      command: docker compose --verbose -f .docker/prod/build.docker-compose.yaml push platform
>>>>>>> 6df526d95 (wip: fix image env):.circleci/config/jobs/docker-platform.yml
