executor: docker-node-amd64

resource_class: large

environment:
  NODE_OPTIONS: --max-old-space-size=6144

steps:
  - restore-workspace
    # This step ensures that Docker commands run in this job will execute on a remote Docker engine.
  - setup_remote_docker:
      docker_layer_caching: true
  - run:
      name: Setup Docker Buildx
      command: |
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap
  # Build for AMD64 architecture since DigitalOcean Kubernetes only supports AMD64 nodes, not ARM
  - run:
      name: 'Build and Push Web Docker Image'
      command: |
        # Debug: Check if AUTH0 variables are available in environment
        echo "Checking AUTH0 environment variables..."
        echo "AUTH0_DOMAIN is: ${AUTH0_DOMAIN:-(not set)}"
        echo "AUTH0_CLIENT_ID is: ${AUTH0_CLIENT_ID:-(not set)}"
        # Run bake with environment variables
        docker buildx bake --file .docker/prod/base.bake.hcl --file .docker/prod/web.bake.hcl --push --progress=plain
