executor: docker-node
resource_class: medium
steps:
  - restore-workspace
    # This step ensures that Docker commands run in this job will execute on a remote Docker engine.
  - setup_remote_docker:
      docker_layer_caching: true
  - run:
      name: 'Build api Docker image'
      command: (./scripts/docker/prod/build-api.sh)
      # command: docker compose --verbose -f .docker/prod/build.docker-compose.yaml build api
  - run:
      name: 'Push Docker Image'
      command: docker compose --verbose -f .docker/prod/build.docker-compose.yaml push api
