parameters:
  resource_class:
    type: string
  max_old_space_size:
    type: integer

executor: docker-node-neo4j

resource_class: << parameters.resource_class >>

environment:
  NODE_OPTIONS: --max-old-space-size=<< parameters.max_old_space_size >>

parallelism: 4
steps:
  - restore-workspace
  - setup-neo4j
  - run: pnpm npx playwright install-deps
  # - setup_remote_docker:
  #     version: default
  # No need since we're not building anything
  # Also very expensive in terms of storage
  # docker_layer_caching: true
  - run:
      name: 'Run E2E Tests'
      # https://github.com/cypress-io/circleci-orb/issues/386
      # command: pnpm nx e2e web-e2e -c ci --verbose
      no_output_timeout: 15m
      command: |
        SHARD="$((${CIRCLE_NODE_INDEX}+1))"

        echo $SHARD;
        echo $CIRCLE_NODE_TOTAL;

        pnpm nx e2e web-e2e -c ci --shard=${SHARD}/${CIRCLE_NODE_TOTAL}
  - store_artifacts:
      path: ~/project/dist/.playwright/apps/web-e2e/playwright-report
      destination: playwright-report
  #   - store_artifacts:
  #       path: ~/project/dist/.playwright/apps/web-e2e/src/screenshots
  #       destination: playwright/screenshots
  #   - store_artifacts:
  #       path: ~/project/dist/.playwright/apps/web-e2e/src/data
  #       destination: playwright/data
  - store_test_results:
      path: ~/project/dist/.playwright/apps/web-e2e/test-output
