executor: docker-node-neo4j
resource_class: large
# Cypress requires record for parallel to work according to https://github.com/cypress-io/cypress/issues/2520
parallelism: 4
steps:
  - restore-workspace
  - setup_remote_docker:
      version: default
      # No need since we're not building anything
      # Also very expensive in terms of storage
      # docker_layer_caching: true
  - run: npx cypress install
  - run: npx cypress verify
  - run:
      name: 'Run E2E Tests'
      command: npx nx e2e platform-e2e -c ci
  - store_artifacts:
      path: ~/project/apps/platform-e2e/src/videos
      destination: cypress/videos
  - store_artifacts:
      path: ~/project/apps/platform-e2e/src/screenshots
      destination: cypress/screenshots
  - store_artifacts:
      path: ~/project/apps/platform-e2e/src/data
      destination: cypress/data
  - store_test_results:
      path: ./tmp/reports/e2e
