executor: docker-node-neo4j
resource_class: large
# Cypress requires record for parallel to work according to https://github.com/cypress-io/cypress/issues/2520
parallelism: 4
steps:
  - restore-workspace
  - setup_remote_docker:
      version: default
      # No need since we're not building anything
      # Also very expensive in terms of storage
      # docker_layer_caching: true
  - run: pnpm cypress install
  - run: pnpm cypress verify
  - run:
      name: 'Run E2E Tests'
      environment:
        # https://github.com/cypress-io/circleci-orb/issues/386
      command: |
        echo 'export CI_BUILD_ID="$(echo ${CIRCLE_SHA1:0:8})-${CIRCLE_BUILD_NUM}"' >> "$BASH_ENV"
        source "$BASH_ENV"
        echo "CI Build ID: $CI_BUILD_ID"
        pnpm nx e2e e2e -c ci --ci-build-id=$CI_BUILD_ID
  - store_artifacts:
      path: ~/project/apps/e2e/src/videos
      destination: cypress/videos
  - store_artifacts:
      path: ~/project/apps/e2e/src/screenshots
      destination: cypress/screenshots
  - store_artifacts:
      path: ~/project/apps/e2e/src/data
      destination: cypress/data
  - store_test_results:
      path: ./tmp/reports/e2e
