executor: docker-node-amd64

resource_class: small

steps:
  - run:
      name: Trigger Flux reconciliation via webhook
      command: |
        # Trigger Flux webhook to reconcile
        curl -X POST \
          -H "Host: flux.codelab.app" \
          ${FLUX_WEBHOOK_URL} \
          --fail \
          --show-error

        echo "Flux webhook triggered successfully"