executor: docker-node-amd64

resource_class: small

steps:
  - run:
      name: Trigger Flux reconciliation via webhook
      command: |
        # Trigger Flux webhook to reconcile
        curl -X POST ${FLUX_WEBHOOK_URL} \
          -H "Content-Type: application/json" \
          -d '{"action": "reconcile"}' \
          --fail \
          --show-error

        echo "Flux webhook triggered successfully"