parameters:
  resource_class:
    type: string
  max_old_space_size:
    type: integer

executor: docker-node-neo4j-arm64

resource_class: << parameters.resource_class >>

environment:
  NODE_OPTIONS: --max-old-space-size=<< parameters.max_old_space_size >>
  NX_CACHE_DIRECTORY: .nx/cache-integration

steps:
  - restore-workspace-database
  - restore-nx-cache:
      cache_name: integration
  - setup-neo4j
  # - clear-jest-cache
  - run:
      name: 'Run Integration Tests'
      command: pnpm cli tasks int --stage ci
      no_output_timeout: 10m
      environment:
        JEST_JUNIT_OUTPUT_DIR: ./tmp/reports/test-integration
        # JEST_JUNIT_OUTPUT_NAME: 'integration-specs-results.xml'
  - save-nx-cache:
      cache_name: integration
  - store_test_results:
      path: ./tmp/reports/test-integration
