# Can't build with machine image, causes build issues
executor: docker-node
resource_class: large
steps:
  - checkout
  - setup-env
  - install-nvm
  - install-pnpm
  - install-packages
  - build-repo
  # This is required since dist depends on code other than pnpm-lock.yam
  # Instead of this can use nx caching
  - persist_to_workspace:
      root: ~/
      paths:
        # Using too much workspace storage, eating up credits
        # - project/node_modules
        # Seems only cli is needed, we can use nx cloud for others
        - project/dist/apps/cli
