executor: docker-node-arm64

parameters:
  stage:
    type: enum
    enum: ['prod', 'ci']

steps:
  - restore-workspace-infra
  - run:
      name: 'Terraform Init'
      command: pnpm cli terraform --stage << parameters.stage >> init
  - run:
      name: 'Terraform Apply'
      command: pnpm cli terraform --stage << parameters.stage >> --autoApprove apply
