parameters:
  resource_class:
    type: string

executor: docker-node-arm64

resource_class: << parameters.resource_class >>

steps:
  - restore-workspace
  - run:
      name: 'Run tsc Check'
      command: pnpm nx run-many --target=tsc-check --target=tsc-check:spec
