executor: docker-node
resource_class: medium
steps:
  - init-repo
  - run:
      name: 'Run Unit Tests'
      command: yarn cli tasks unit --stage ci
  # Upload test results
  - store_test_results:
      path: /tmp/test-reports
