import {
  Form,
  handleFormSubmit,
} from '@codelab/frontend-presentation-components-form'
import type { ObjectLike } from '@codelab/shared/abstract/types'
import type { JSONSchemaType } from 'ajv'
import { observer } from 'mobx-react-lite'
import React, { useMemo } from 'react'
import { mergeDeep } from 'remeda'
import type { InterfaceFormProps } from './types'
import { uiPropertiesContainer } from './ui-properties'

/**
 * Uniforms form generated by an {@link IInterfaceType}
 */
export const InterfaceForm = observer(
  <TData, TResponse>({
    autosave,
    children,
    context,
    initialSchema,
    interfaceType,
    model,
    onChange,
    onSubmit,
    onSubmitError,
    onSubmitSuccess,
    setIsLoading,
    submitField,
    submitRef,
  }: React.PropsWithChildren<InterfaceFormProps<TData, TResponse>>) => {
    const formSchema = useMemo(() => {
      const jsonSchema = interfaceType.toJsonSchema({
        ...context,
        ui: uiPropertiesContainer,
      })

      return mergeDeep(initialSchema ?? {}, jsonSchema as ObjectLike)
    }, [interfaceType, interfaceType.fields, initialSchema])

    return (
      <Form
        autosave={autosave}
        model={model}
        onChange={onChange}
        onSubmit={handleFormSubmit<TData, TResponse>(
          onSubmit,
          setIsLoading,
          onSubmitSuccess,
          onSubmitError,
        )}
        onSubmitError={onSubmitError}
        onSubmitSuccess={onSubmitSuccess}
        schema={formSchema as JSONSchemaType<unknown>}
        submitField={submitField}
        submitRef={submitRef}
        // TODO: Need to find a way to have a domain key in this case
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        uiKey={'interface-form' as any}
      >
        {children}
      </Form>
    )
  },
)

InterfaceForm.displayName = 'InterfaceForm'
