---
# Deploy configuration files

# ============================================================================
# DigitalOcean Configuration
# ============================================================================

- name: Configure doctl
  template:
    src: templates/doctl-config.yaml.j2
    dest: /root/.config/doctl/config.yaml
    mode: '0600'

# ============================================================================
# Consul Configuration
# ============================================================================

- name: Copy Consul base configuration
  copy:
    src: '../../modules/consul-base/consul-base.hcl'
    dest: /etc/consul.d/consul-base.hcl
    owner: consul
    group: consul
    mode: '0640'
  notify: restart consul

- name: Create Consul encryption configuration
  copy:
    content: 'encrypt = "{{ consul_encrypt_key }}"'
    dest: /etc/consul.d/encryption.hcl
    owner: consul
    group: consul
    mode: '0640'
  notify: restart consul

# ============================================================================
# Consul-Template Configurations
# ============================================================================

# Docker service configuration management via Consul-Template
- name: Copy Consul-Template configuration
  copy:
    src: '../../modules/consul-base/docker.consul-template.hcl'
    dest: /etc/consul-template/docker.consul-template.hcl
    mode: '0644'

# Alloy (log shipping) configuration management via Consul-Template
- name: Copy Alloy configuration template
  copy:
    src: '../../modules/alloy/config.alloy.ctmpl'
    dest: /etc/consul-template/config.alloy.ctmpl
    mode: '0644'

- name: Copy Alloy consul-template configuration
  copy:
    src: '../../modules/alloy/alloy.consul-template.hcl'
    dest: /etc/consul-template/alloy.consul-template.hcl
    mode: '0644'

# ============================================================================
# Systemd Service Definitions
# ============================================================================

# Docker-related Services
- name: Deploy Docker Consul-Template systemd service
  copy:
    src: '../../modules/docker/docker-consul-template.service'
    dest: /etc/systemd/system/docker-consul-template.service
    mode: '0644'
  notify: reload systemd

- name: Deploy Docker login systemd service
  copy:
    src: '../../modules/doctl/docker-login.service'
    dest: /etc/systemd/system/docker-login.service
    mode: '0644'
  notify: reload systemd

# Monitoring/Logging Services (Alloy)
- name: Deploy Alloy systemd service
  copy:
    src: '../../modules/alloy/alloy.service'
    dest: /etc/systemd/system/alloy.service
    mode: '0644'
  notify: reload systemd

- name: Deploy Alloy consul-template systemd service
  copy:
    src: '../../modules/alloy/alloy-consul-template.service'
    dest: /etc/systemd/system/alloy-consul-template.service
    mode: '0644'
  notify: reload systemd
