---
# Deploy configuration files

- name: Configure doctl
  template:
    src: templates/doctl-config.yaml.j2
    dest: /root/.config/doctl/config.yaml
    mode: '0600'

- name: Copy Consul base configuration
  copy:
    src: '../../modules/consul-base/consul-base.hcl'
    dest: /etc/consul.d/consul-base.hcl
    owner: consul
    group: consul
    mode: '0640'
  notify: restart consul

- name: Create Consul encryption configuration
  copy:
    content: 'encrypt = "{{ consul_encrypt_key }}"'
    dest: /etc/consul.d/encryption.hcl
    owner: consul
    group: consul
    mode: '0640'
  notify: restart consul

- name: Copy Consul-Template configuration
  copy:
    src: '../../modules/consul-base/docker.consul-template.hcl'
    dest: /etc/consul-template/docker.consul-template.hcl
    mode: '0644'

- name: Copy Alloy configuration
  copy:
    src: '../../modules/alloy/config.alloy'
    dest: /etc/alloy/config.alloy
    mode: '0644'

- name: Deploy Consul systemd service
  copy:
    src: '../../modules/consul-base/consul.service'
    dest: /etc/systemd/system/consul.service
    mode: '0644'
  notify: reload systemd

- name: Deploy Docker Consul-Template systemd service
  copy:
    src: '../../modules/docker/docker-consul-template.service'
    dest: /etc/systemd/system/docker-consul-template.service
    mode: '0644'
  notify: reload systemd

- name: Deploy Alloy systemd service
  copy:
    src: '../../modules/alloy/alloy.service'
    dest: /etc/systemd/system/alloy.service
    mode: '0644'
  notify: reload systemd

- name: Deploy Docker login systemd service
  copy:
    src: '../../modules/doctl/docker-login.service'
    dest: /etc/systemd/system/docker-login.service
    mode: '0644'
  notify: reload systemd

- name: Deploy remove-packer-marker service for first boot
  copy:
    src: files/remove-packer-marker.service
    dest: /etc/systemd/system/remove-packer-marker.service
    mode: '0644'
  notify: reload systemd
