---
# System optimization

- name: Set vm.max_map_count for Elasticsearch
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes

- name: Set net.core.somaxconn for high connection workloads
  sysctl:
    name: net.core.somaxconn
    value: '1024'
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes

- name: Mask automatic update services
  systemd:
    name:
      - apt-daily.service
      - apt-daily-upgrade.service
      - unattended-upgrades.service
    masked: yes
