---
# System optimization

- name: Set vm.max_map_count for Elasticsearch
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes

- name: Set net.core.somaxconn for high connection workloads
  sysctl:
    name: net.core.somaxconn
    value: '1024'
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes

- name: Mask apt-daily service
  systemd:
    name: apt-daily.service
    masked: yes

- name: Mask apt-daily-upgrade service
  systemd:
    name: apt-daily-upgrade.service
    masked: yes

- name: Mask unattended-upgrades service
  systemd:
    name: unattended-upgrades.service
    masked: yes
