---
# Service management

- name: Flush handlers before enabling services
  meta: flush_handlers

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

# Install unmask service for production droplets
- name: Copy unmask-services systemd service
  copy:
    src: '../unmask-services.service'
    dest: /etc/systemd/system/unmask-services.service
    mode: '0644'

- name: Enable unmask-services service
  systemd:
    name: unmask-services
    enabled: yes
    daemon_reload: yes

# ============================================================================
# Enable and mask services (masked services won't start during build)
# ============================================================================

- name: Enable Consul service
  systemd:
    name: consul
    enabled: yes
    masked: yes

- name: Enable Docker login service
  systemd:
    name: docker-login
    enabled: yes
    masked: yes

- name: Enable Docker Consul-Template service
  systemd:
    name: docker-consul-template
    enabled: yes
    masked: yes

- name: Enable Alloy consul-template service
  systemd:
    name: alloy-consul-template
    enabled: yes
    masked: yes

- name: Enable Alloy service
  systemd:
    name: alloy
    enabled: yes
    masked: yes
