---
# Enable essential services that should run during build and on first boot

- name: Flush handlers before enabling services
  meta: flush_handlers

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

# Install service to enable services on first boot
- name: Copy enable-services systemd service
  copy:
    src: '../enable-services.service'
    dest: /etc/systemd/system/enable-services.service
    mode: '0644'

- name: Enable enable-services service
  systemd:
    name: enable-services
    enabled: yes
    daemon_reload: yes
