---
# Service management

- name: Flush handlers before enabling services
  meta: flush_handlers

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Enable all services
  systemd:
    name:
      - consul
      - docker-login
      - docker-consul-template
      - alloy
    enabled: yes
