---
# Service management

- name: Flush handlers before enabling services
  meta: flush_handlers

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Enable Consul service
  systemd:
    name: consul
    enabled: yes

- name: Enable Docker login service
  systemd:
    name: docker-login
    enabled: yes

- name: Enable Docker Consul-Template service
  systemd:
    name: docker-consul-template
    enabled: yes

- name: Enable Alloy service
  systemd:
    name: alloy
    enabled: yes
