---
# Disable services to prevent startup during build
#
# Why we use 'enabled: no' instead of 'masked: yes':
# - Systemd masking creates a symlink from the service file to /dev/null
# - Our playbooks copy real service files to /etc/systemd/system/ first
# - Masking fails with "File already exists" because it can't replace the
#   real file with a symlink
# - Using 'state: stopped' and 'enabled: no' achieves the same goal without
#   symlink conflicts
#
# Services will be enabled and started by enable-services.service on first boot

- name: Stop and disable Consul service during build
  systemd:
    name: consul
    state: stopped
    enabled: no

- name: Stop and disable Docker login service during build
  systemd:
    name: docker-login
    state: stopped
    enabled: no

- name: Stop and disable Docker Consul-Template service during build
  systemd:
    name: docker-consul-template
    state: stopped
    enabled: no

- name: Stop and disable Alloy consul-template service during build
  systemd:
    name: alloy-consul-template
    state: stopped
    enabled: no

- name: Stop and disable Alloy service during build
  systemd:
    name: alloy
    state: stopped
    enabled: no
