---
# Service management

- name: Flush handlers before enabling services
  meta: flush_handlers

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

# Install unmask service for production droplets
- name: Copy unmask-services systemd service
  copy:
    src: '../unmask-services.service'
    dest: /etc/systemd/system/unmask-services.service
    mode: '0644'

- name: Enable unmask-services service
  systemd:
    name: unmask-services
    enabled: yes
    daemon_reload: yes

# ============================================================================
# Mask services to prevent startup during build
# Services will be unmasked and started by unmask-services on boot
# ============================================================================

- name: Mask Consul service to prevent startup during build
  systemd:
    name: consul
    masked: yes

- name: Mask Docker login service to prevent startup during build
  systemd:
    name: docker-login
    masked: yes

- name: Mask Docker Consul-Template service to prevent startup during build
  systemd:
    name: docker-consul-template
    masked: yes

- name: Mask Alloy consul-template service to prevent startup during build
  systemd:
    name: alloy-consul-template
    masked: yes

- name: Mask Alloy service to prevent startup during build
  systemd:
    name: alloy
    masked: yes
