---
# Verify pre-snapshot state - reusable task for all images

- name: Copy pre-snapshot verification script
  copy:
    src: '{{ playbook_dir }}/../../scripts/verify-pre-snapshot.sh'
    dest: /tmp/verify-pre-snapshot.sh
    mode: '0755'

- name: Run pre-snapshot verification
  command: /tmp/verify-pre-snapshot.sh
  register: verify_result

- name: Show verification results
  debug:
    msg: '{{ verify_result.stdout_lines }}'

- name: Remove verification script
  file:
    path: /tmp/verify-pre-snapshot.sh
    state: absent
