# TODO: figure out how to avoid duplication here and in root graphql-let
overwrite: true
hooks:
  afterAllFileWrite:
    - yarn prettier --write
    - yarn eslint --ext ts --fix
cacheDir: ../../.gqlcodegen
TSConfigFile: ../../tsconfig.base.json

schema: ../../schema.api.graphql
documents:
  - ../../libs/**/modules/**/*.api.graphql
  - ../../libs/frontend/view/**/*.api.graphql
  - ../../apps/web/**/*.api.graphql
  - ../../apps/cli/**/*.api.graphql
  - ../../apps/web-e2e/**/*.api.graphql
plugins:
  - typescript-operations
  - typescript-react-apollo
#  - typescript-document-nodes
config:
  # Switch off if have deeply nested issues
  inlineFragmentTypes: combine
  documentVariableSuffix: Gql
  gqlImport: '@apollo/client#gql'
  skipTypename: true
  strictScalars: true
  defaultScalarType: unknown
  withRefetchFn: true
  scalars:
    uuid: string
    json: Record<string, any>
    jsonb: Record<string, any>
    DateTime: string
    Int64: number
    _Any: any
    Void: void
