---
- name: Provision base image
  hosts: default
  become: yes
  gather_facts: yes
  vars_files:
    - vars/main.yml

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart docker
      systemd:
        name: docker
        state: restarted
        enabled: yes

    - name: restart consul
      systemd:
        name: consul
        state: stopped # Don't actually restart during Packer build. If we started Consul,
        enabled:
          yes # it would try to gracefully leave its cluster during shutdown,
          # timing out after 5 minutes since no cluster exists in build env.

  pre_tasks:
    - name: Wait for cloud-init to complete
      command: cloud-init status --wait
      failed_when: false
      changed_when: false

    - name: Configure dpkg
      command: dpkg --configure -a
      failed_when: false
      changed_when: false

  tasks:
    # Phase 1: Repository Setup
    - name: Setup repositories
      include_tasks: tasks/repositories.yml
      tags: ['repositories']

    # Phase 2: Package Installation
    - name: Install packages
      include_tasks: tasks/packages.yml
      tags: ['packages']

    # Phase 3: Directory Structure
    - name: Create directory structure
      include_tasks: tasks/directories.yml
      tags: ['directories']

    # Phase 4: Configuration Files
    - name: Deploy configurations
      include_tasks: tasks/configurations.yml
      tags: ['configurations']

    # Phase 5: Service Management
    - name: Setup services
      include_tasks: tasks/services.yml
      tags: ['services']

    # Phase 6: System Optimization
    - name: Optimize system
      include_tasks: tasks/optimization.yml
      tags: ['optimization']

    # Phase 7: Cleanup
    - name: Clean system
      include_tasks: tasks/cleanup.yml
      tags: ['cleanup']
