---
# Reusable tasks for setting up Caddy with Docker Compose
# Include this file in any image that needs Caddy reverse proxy

- name: Create caddy directory
  file:
    path: /opt/caddy
    state: directory
    mode: '0755'

- name: Create modules directory structure for Docker Compose includes
  file:
    path: /modules/caddy
    state: directory
    mode: '0755'

- name: Copy Caddy Docker Compose module
  copy:
    src: '{{ playbook_dir }}/../../modules/caddy/docker-compose.caddy.yaml'
    dest: /modules/caddy/docker-compose.caddy.yaml
    mode: '0644'
# Note: The Caddyfile should be copied by the image-specific playbook
# since each service has its own Caddyfile configuration
