schema: 'schema.api.v2.graphql'
documents:
  - libs/**/modules/**/*.graphql
# extensions:
#   - endpoints:
#     'Nest API Graphql Endpoint':
#       url: '${env:CODELAB_API_ENDPOINT}/graphql'
#       headers:
#         user-agent: 'JS Graphql'
#       introspect: true
