schema: 'schema.api.graphql'
documents:
  - libs/**/modules/**/*.api.graphql
  - apps/web/**/*.api.graphql
  - apps/web-e2e/**/*.api.graphq
extensions:
  - endpoints:
    'Nest API Graphql Endpoint':
      url: '${env:CODELAB_API_ENDPOINT}/graphql'
      headers:
        user-agent: 'JS Graphql'
      introspect: true
