overwrite: true
hooks:
  afterAllFileWrite:
    - yarn prettier --write
    - yarn eslint --ext ts --fix

generates:
  schema.dgraph.graphql:
    schema:
      - ${CODELAB_DGRAPH_GRAPHQL_ENDPOINT}:
    plugins:
      - schema-ast

  libs/codegen/graphql/src/graphql-client-api.generated.ts:
    schema:
      - ${CODELAB_API_ENDPOINT}/graphql:
    documents:
      - libs/modules/**/*.api.graphql
      - apps/web/**/*.api.graphql
      - apps/web-e2e/**/*.api.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - typescript-document-nodes
    scalars:
      Void: void
    config:
      # defaultBaseOptions:
      #   operationName: 'api'
      documentVariableSuffix: 'Gql'
      gqlImport: '@apollo/client#gql'
      skipTypename: true
      strictScalars: true
      defaultScalarType: unknown
      withRefetchFn: true
