# pnpMode: loose
# Waiting for pnp support with NX https://github.com/nrwl/nx/issues/2386
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.1.1.cjs
npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com/
    npmAlwaysAuth: true
    npmAuthToken: EE2242B7-FC5E-4CC0-9630-F83CE6524319
