module.exports = {
  projects: [
    '<rootDir>/apps/api',
    '<rootDir>/apps/web',
    '<rootDir>/libs/alpha/core/graph',
    '<rootDir>/libs/alpha/core/node',
    '<rootDir>/libs/alpha/core/props',
    '<rootDir>/libs/alpha/core/renderer',
    '<rootDir>/libs/alpha/core/traversal',
    '<rootDir>/libs/alpha/core/tree',
    '<rootDir>/libs/alpha/ui/antd',
    '<rootDir>/libs/alpha/ui/d3',
    '<rootDir>/libs/backend',
    '<rootDir>/libs/frontend',
    '<rootDir>/libs/tools/eslint-config-codelab',
    '<rootDir>/libs/alpha/shared/interface/props',
    '<rootDir>/libs/alpha/shared/interface/graph',
    '<rootDir>/libs/alpha/shared/interface/node',
    '<rootDir>/libs/alpha/shared/interface/tree',
  ],
}
