# Parallel Slack notification https://github.com/CircleCI-Public/slack-orb/issues/305
# https://support.circleci.com/hc/en-us/articles/360047082992-Send-slack-notification-at-end-of-workflow

#slack-fail-post-step: &slack-fail-post-step
#  post-steps:
#    #    - swissknife/wait_for_job:
#    #        job-name: install-and-build-workspace,lint,unit,e2e,codegen
#    - slack/notify:
#        event: fail
#        channel: $SLACK_CHANNEL_UPDATE
#        template: basic_fail_1

version: 2.1

orbs:
  slack: circleci/slack@4.12.5
  nx: nrwl/nx@1.6.2
  node: circleci/node@7.1.0
  queue: eddiewebb/queue@2.2.1
  swissknife: roopakv/swissknife@0.69.0
  terraform: circleci/terraform@3.2.1

working_directory: ~/project

# Global environment variables for all jobs
environment:
  # Disable Nx daemon to prevent conflicts when jobs run in parallel
  # The daemon is a global process that can cause race conditions and cache
  # confusion when multiple jobs try to use it simultaneously
  NX_DAEMON: false
  CACHE_VERSION: 0.1
