export * from './create-tag.input'
export * from './create-tag.request'
export * from './create-tag.service'
export * from './tests/create-tag.api.graphql.gen'
export * from './tests/create-tag.data'
export * from './tests/create-tag.data'
