description: 'Build Repo'
steps:
  # - restore_cache:
  #     name: 'Restore NX Cache'
  #     keys:
  #       - nx-cache
  # - run:
  #     name: 'Monitor NX Cache Size'
  #     command: ./scripts/nx/reset-cache.sh
  # Can't use `pnpm cli` doesn't exist yet
  - run: pnpm nx affected --target=build --parallel=3 -c ci --nx-bail -- base=$NX_BASE --head=$NX_HEAD
  # - save_cache:
  #     name: 'Save NX Cache'
  #     # nx doesn't use `lockfile.hash` anymore
  #     # key: nx-cache-{{ checksum ".nx/cache/lockfile.hash" }}
  #     key: nx-cache
  #     paths:
  #       - ~/project/.nx/cache
  #       # CI caching guide https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching
  #       - ~/project/dist/apps/web/.next/cache
  #       - ~/project/dist/apps/sites/.next/cache
  #       - ~/project/dist/apps/landing/.next/cache
