description: 'Build Repo'
steps:
  # - restore_cache:
  #     name: 'Restore NX Cache'
  #     keys:
  #       - nx-cache
  # - run:
  #     name: 'Monitor NX Cache Size'
  #     command: ./scripts/nx/reset-cache.sh
  # Can't use `pnpm cli` doesn't exist yet
  - nx/set-shas:
      main-branch-name: 'master'
  - run: echo $CIRCLE_API_TOKEN
  # https://nx.dev/ci/intro/tutorials/circle#connect-to-circle-ci
  # - run: pnpm nx connect
  # - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"
  - run: pnpm nx affected --target=build --parallel=2 -c ci --nx-bail
  # - save_cache:
  #     name: 'Save NX Cache'
  #     # nx doesn't use `lockfile.hash` anymore
  #     # key: nx-cache-{{ checksum ".nx/cache/lockfile.hash" }}
  #     key: nx-cache
  #     paths:
  #       - ~/project/.nx/cache
  #       # CI caching guide https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching
  #       - ~/project/dist/apps/web/.next/cache
  #       - ~/project/dist/apps/sites/.next/cache
  #       - ~/project/dist/apps/landing/.next/cache
