# Can't use `pnpm cli` doesn't exist yet
# We split `apps` and `libs` along with their cache location
# IMPORTANT: Do not use --nx-bail flag as it prevents Nx Cloud from properly storing cache artifacts

description: 'Build Nx Apps'
steps:
  - nx/set-shas:
      main-branch-name: 'master'
  # Restore caches separately
  - restore_cache:
      name: 'Restore Nx Cache'
      keys:
        - nx-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}
        - nx-cache-{{ .Environment.CIRCLE_BRANCH }}-
        - nx-cache-
  - restore_cache:
      name: 'Restore Next.js Cache'
      keys:
        - nextjs-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}
        - nextjs-cache-{{ .Environment.CIRCLE_BRANCH }}-
        - nextjs-cache-
  - run:
      name: 'Check cache after restore'
      command: |
        echo "=== After cache restore ==="
        echo "Checking .nx/cache:"
        ls -la .nx/cache/ 2>/dev/null | head -20 || echo "No .nx/cache directory"
        echo ""
        echo "Cache size:"
        du -sh .nx/cache/ 2>/dev/null || echo "0"
        echo ""
        echo "Checking Next.js cache:"
        ls -la dist/apps/web/.next/cache/ 2>/dev/null | head -10 || echo "No Next.js cache"
  - run:
      name: 'Build Nx Apps (web, api)'
      command: pnpm nx run-many --target=build --projects=web,api -c ci
  - run:
      name: 'Check build output sizes'
      command: |
        echo "=== Build output sizes ==="
        echo "Total web build size:"
        du -sh dist/apps/web/ 2>/dev/null || echo "No web build"
        echo ""
        echo "Web build breakdown:"
        du -sh dist/apps/web/* 2>/dev/null | sort -hr || echo "No files"
        echo ""
        echo "Next.js directories:"
        du -sh dist/apps/web/.next/* 2>/dev/null | sort -hr || echo "No .next directory"
        echo ""
        echo "Total API build size:"
        du -sh dist/apps/api/ 2>/dev/null || echo "No api build"
        echo ""
        echo "=== Check what Nx is trying to cache ==="
        echo "Files in dist/apps/web (excluding .next/cache):"
        find dist/apps/web -type f -not -path "*/\.next/cache/*" | wc -l
        echo ""
        echo "Size without .next/cache:"
        du -sh --exclude=.next/cache dist/apps/web/ 2>/dev/null || echo "Cannot calculate"
  # Save caches separately - Nx cache for Nx Cloud, Next.js cache for build optimization
  - save_cache:
      name: 'Save Nx Cache'
      key: nx-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}
      paths:
        - .nx/cache
  - save_cache:
      name: 'Save Next.js Cache'
      key: nextjs-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}
      paths:
        - dist/apps/web/.next/cache
  - persist_to_workspace:
      root: ~/
      paths:
        - project/dist/apps/web
        - project/dist/apps/api
