# Can't use `pnpm cli` doesn't exist yet

description: 'Build Nx Libs'
steps:
  - nx/set-shas:
      main-branch-name: 'master'
  # Removed CircleCI cache for Nx - Nx Cloud handles all Nx caching
  # This prevents ENOENT errors when Nx Cloud tries to upload artifacts
  - run:
      command: pnpm nx run-many --target=build --all --exclude=web,api -c ci
  # Removed CircleCI cache save - Nx Cloud handles all Nx caching
