# Can't use `pnpm cli` doesn't exist yet
# We split `apps` and `libs` along with their cache location
# IMPORTANT: Do not use --nx-bail flag as it prevents Nx Cloud from properly storing cache artifacts

description: 'Build Nx Apps'
steps:
  - nx/set-shas:
      main-branch-name: 'master'
  - restore-nx-cache:
      cache_name: apps
  - run:
      name: 'Build Nx Apps (web, api)'
      command: pnpm nx run-many --target=build --projects=web,api -c ci
  - save-nx-cache:
      cache_name: apps
      extra_paths: dist/apps/web/.next/cache
  - persist_to_workspace:
      root: ~/
      paths:
        - project/dist/apps/web
        - project/dist/apps/api
