# Can't use `pnpm cli` doesn't exist yet
# We split `apps` and `libs` along with their cache location

description: 'Build Nx Apps'
steps:
  - nx/set-shas:
      main-branch-name: 'master'
  # Only restore Next.js cache (libs build fast enough with just Nx Cloud)
  - restore_cache:
      name: 'Restore Nx Apps Cache'
      keys:
        - nx-apps-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}
        - nx-apps-cache-{{ .Environment.CIRCLE_BRANCH }}-
        - nx-apps-cache-
  - run:
      command: pnpm nx run-many --target=build --projects=web,api -c ci
  # Save Nx cache for local caching (works alongside Nx Cloud)
  - save_cache:
      name: 'Save Nx Apps Cache'
      key: nx-apps-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}
      paths:
        - .nx/cache
        - dist/apps/web/.next/cache
  - persist_to_workspace:
      root: .
      paths:
        - dist/apps/web
        - dist/apps/api
