description: 'Build Repo'
steps:
  # - run:
  #     name: 'Monitor NX Cache Size'
  #     command: ./scripts/nx/reset-cache.sh
  # Can't use `pnpm cli` doesn't exist yet
  - nx/set-shas:
      main-branch-name: 'master'
  - restore_cache:
      name: 'Restore NX Cache'
      keys:
        - nx-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}
        - nx-cache-{{ .Environment.CIRCLE_BRANCH }}-
        - nx-cache-
  - run:
      command: (./scripts/nx/reset-cache.sh)
  - run:
      command: pnpm nx run-many --target=build --projects=web,api -c ci --nx-bail
  # CI caching guide https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching
  - save_cache:
      name: 'Save NX Cache'
      key:
        nx-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}
        # nx doesn't use `lockfile.hash` anymore, so move the pnpm
        # - nx-cache-{{ checksum ".nx/cache/lockfile.hash" }}
      paths:
        - ~/project/.nx/cache
        # https://github.com/nrwl/nx/issues/5221
        - ~/project/dist/apps/web/.next/cache
        # - ~/project/dist/apps/sites/.next/cache
        # - ~/project/dist/apps/landing/.next/cache
  # Can also use cache, but we're using workspace for simplicity
  - persist_to_workspace:
      root: ~/
      paths:
        # Using too much workspace storage, eating up credits. Use cache instead
        # - project/node_modules
        - project/dist/apps/cli
        - project/dist/apps/web
