# Can't use `pnpm cli` doesn't exist yet

description: 'Build Nx Libs'
steps:
  - nx/set-shas:
      main-branch-name: 'master'
  # No local cache needed - libs build fast enough with just Nx Cloud
  - run:
      command: pnpm nx run-many --target=build --all --exclude=web,api -c ci
