# Can't use `pnpm cli` doesn't exist yet
# We split `apps` and `libs` along with their cache location

description: 'Build Nx Apps'
steps:
  - nx/set-shas:
      main-branch-name: 'master'
  # Only restore Next.js cache, not Nx cache (Nx Cloud handles Nx caching)
  - restore_cache:
      name: 'Restore Next.js Cache'
      keys:
        - nextjs-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}
        - nextjs-cache-{{ .Environment.CIRCLE_BRANCH }}-
        - nextjs-cache-
  # - run:
  #     name: 'Monitor NX Cache Size'
  #     command: (./scripts/nx/reset-cache.sh)
  - run:
      command: pnpm nx run-many --target=build --projects=web,api -c ci --nx-bail
  # https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#circleci
  # Only save Next.js cache, not Nx cache (Nx Cloud handles Nx caching)
  # https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#circleci
  - save_cache:
      name: 'Save Next.js Cache'
      key: nextjs-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}
      paths:
        - dist/apps/web/.next/cache
  - persist_to_workspace:
      root: ~/
      paths:
        - project/dist/apps/web
        - project/dist/apps/api
