# Can't use `pnpm cli` doesn't exist yet
# We split `apps` and `libs` along with their cache location
# IMPORTANT: Do not use --nx-bail flag as it prevents Nx Cloud from properly storing cache artifacts

description: 'Build Nx Apps'
steps:
  - nx/set-shas:
      main-branch-name: 'master'
  # Restore Nx Apps cache (includes Next.js cache)
  - restore_cache:
      name: 'Restore Nx Apps Cache'
      keys:
        - nx-apps-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}
        - nx-apps-cache-{{ .Environment.CIRCLE_BRANCH }}-
        - nx-apps-cache-
  - run:
      name: 'Build Nx Apps (web, api)'
      command: pnpm nx run-many --target=build --projects=web,api -c ci
  # Save Nx Apps cache (includes Next.js cache)
  - save_cache:
      name: 'Save Nx Apps Cache'
      key: nx-apps-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}
      paths:
        - .nx/cache-apps # Must match NX_CACHE_DIRECTORY in command environment
        - dist/apps/web/.next/cache
  - persist_to_workspace:
      root: ~/
      paths:
        - project/dist/apps/web
        - project/dist/apps/api
