# Can't use `pnpm cli` doesn't exist yet

description: 'Build Nx Libs'
steps:
  - nx/set-shas:
      main-branch-name: 'master'
  - restore-nx-cache:
      cache_name: libs
  - run:
      name: 'Build Nx Libs'
      command: pnpm nx run-many --target=build --all --exclude=web,api -c ci
  - save-nx-cache:
      cache_name: libs
