description: 'Init Repo'
steps:
  - checkout
  - attach_workspace:
      at: ..
  - restore_cache:
      name: 'Restore Cache'
      keys:
        - npm-cache-{{ checksum "yarn.lock" }}
        - nvm-cache-{{ checksum ".nvmrc" }}
        - nx-cache-{{ checksum "node_modules/.cache/nx/lockfile.hash" }}
  - install-nvm
  - run:
      name: 'Setup Env'
      command: |
        # git settings
        echo 'export GIT_COMMIT_MSG=$(git log --format="format:%s" -n 1 ${CIRCLE_SHA1})' >> $BASH_ENV

        # slack settings
        if [ "$CIRCLE_USERNAME" == "$GITHUB_ANTON_M" ]; then
          echo 'export SLACK_PARAM_MENTIONS=${SLACK_ANTOM_M}' >> $BASH_ENV

        elif [ "$CIRCLE_USERNAME" == "$GITHUB_ASSIM" ]; then
          echo 'export SLACK_PARAM_MENTIONS=${SLACK_ASSIM}' >> $BASH_ENV

        elif [ "$CIRCLE_USERNAME" == "$GITHUB_NGHIA" ]; then
          echo 'export SLACK_PARAM_MENTIONS=${SLACK_NGHIA}' >> $BASH_ENV

        elif [ "$CIRCLE_USERNAME" == "$GITHUB_YASEEN" ]; then
          echo 'export SLACK_PARAM_MENTIONS=${SLACK_YASEEN}' >> $BASH_ENV

        else
          echo 'export SLACK_PARAM_MENTIONS=${SLACK_WEBBER}' >> $BASH_ENV
        fi

        # finally import bash env
        source $BASH_ENV
  - nx/set-shas:
      main-branch-name: master
