description: 'Init Repo'
steps:
  - checkout
  - attach_workspace:
      at: ..
  - restore_cache:
      name: 'Restore NPM Cache'
      keys:
        # We store this only in setup-workspace
        - npm-cache-{{ checksum "yarn.lock" }}
        - nvm-cache-{{ checksum ".nvmrc" }}
  - restore_cache:
      # Need this to run after we restore the npm library
      name: 'Restore NX Cache'
      keys:
        - nx-cache-{{ checksum "node_modules/.cache/nx/lockfile.hash" }}
  - run:
      name: 'Setup Env'
      command: source ~/project/.circleci/config/env.sh
  - run: env
  - nx/set-shas:
      main-branch-name: master
