description: 'Install Terraform'
steps:
  # - restore_cache:
  #     name: 'Restore Terraform Cache'
  #     keys:
  #       # Same as version below
  #       - terraform-cache-1.3.9
  #       - terraform-cache
  - run:
      # Manually install because we can't add `pnpm` to terraform orb
      # https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli
      name: 'Install Terraform'
      command: |
        set -x

        apt-get update && apt-get install -y gnupg software-properties-common

        apt list upgrade

        wget -O- https://apt.releases.hashicorp.com/gpg | \
        gpg --dearmor | \
        tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
        tee /etc/apt/sources.list.d/hashicorp.list

        gpg --no-default-keyring \
        --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
        --fingerprint

        apt update
        apt install -y terraform=1.7.0-*

  # - save_cache:
  #     name: 'Save Terraform Cache'
  #     key: terraform-cache-1.3.9
  #     paths:
  #       - /usr/local/bin/terraform
