# We need to run this before each step, since the core version isn't stored within ~/.pnpm-store
#
# It's better to install per job, rather than persisting /usr/local due to permissions issues
steps:
  - run:
      name: Install pnpm package manager
      command: |
        set -x

        # Install corepack using the correct path
        # https://github.com/pnpm/pnpm/issues/9029
        sudo npm install -g corepack@0.31.0

        sudo corepack enable
        sudo corepack prepare pnpm@9.15.5 --activate
        pnpm config set store-dir ~/.pnpm-store
