# We need to run this before each step, since the core version isn't stored within ~/.pnpm-store
steps:
  - run:
      name: Install pnpm package manager
      command: |
        sudo corepack enable
        sudo corepack prepare pnpm@9.1.1 --activate
        pnpm config set store-dir ~/.pnpm-store

        which pnpm
  # This is required since dist depends on code other than pnpm-lock.yam
  # Instead of this can use nx caching
  - persist_to_workspace:
      root: /
      paths:
        - /usr/local/bin/pnpm
