description: 'Install Packer'
steps:
  - run:
      name: 'Install Packer'
      command: |
        set -x

        curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -

        apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

        apt-get update && apt-get install -y packer
