steps:
  # NPM cache already restored in restore-workspace, which is shared with other jobs. While pnpm cache is only needed in the setup-workspace job
  #
  # The time to restore node_modules is longer than the time saving from installing node_modules again
  #
  - restore_cache:
      name: 'Restore pnpm Package Cache'
      keys:
        - pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
        - pnpm-cache
  # Need to bust cache manually by updating lock file
  - run:
      name: 'Prune pnpm store'
      command: |
        pnpm store path
        pnpm store prune
  - run:
      name: 'Install NPM Packages'
      command: pnpm install --frozen-lockfile
  - run:
      name: 'Debug and update local file dependencies'
      command: |
        set -x  # Enable debug mode to see all commands

        echo "=== Checking dist folder contents ==="
        ls -la dist/libs/tools/workspace/ || echo "dist/libs/tools/workspace not found"

        echo "=== Checking if src folder exists in dist ==="
        ls -la dist/libs/tools/workspace/src/ || echo "src folder not found in dist"

        echo "=== Checking generators folder contents ==="
        find dist/libs/tools/workspace/src/generators -type f -name "*.js" | head -20 || echo "No JS files found"

        echo "=== Checking specific generator path ==="
        ls -la dist/libs/tools/workspace/src/generators/nx-project-config/ || echo "nx-project-config folder not found"

        echo "=== Checking generators.json ==="
        cat dist/libs/tools/workspace/generators.json || echo "generators.json not found"

        echo "=== Current working directory ==="
        pwd

        echo "=== Checking node_modules before cleanup ==="
        ls -la node_modules/@codelab/ | grep tools-workspace || echo "tools-workspace not in node_modules"

        echo "=== Checking pnpm store location ==="
        pnpm store path

        # Remove stale entries from pnpm store for local packages
        pnpm store prune

        # Force pnpm to update symlinks for local file dependencies
        echo "=== Removing old node_modules entries ==="
        rm -rf node_modules/.pnpm/@codelab+tools-workspace*
        rm -rf node_modules/.pnpm/file+dist+libs+tools+workspace*
        rm -rf node_modules/@codelab/tools-workspace

        echo "=== Running pnpm install --force ==="
        pnpm install --force @codelab/tools-workspace

        echo "=== Checking node_modules after install ==="
        ls -la node_modules/@codelab/tools-workspace/ || echo "Failed to install tools-workspace"

        echo "=== Checking symlink target ==="
        readlink -f node_modules/@codelab/tools-workspace || echo "Not a symlink or doesn't exist"

        echo "=== Checking pnpm resolution ==="
        pnpm list @codelab/tools-workspace
  - save_cache:
      name: 'Save pnpm Cache'
      key: pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
      paths:
        - ~/.pnpm-store
  - save_cache:
      name: 'Save node_modules Cache'
      key: node-modules-cache-{{ checksum "pnpm-lock.yaml" }}
      paths:
        - ~/project/node_modules
  # node_modules cache needs to be checked for cache reset before we can save, otherwise nx cache grows too much. This step happens after build
