description: 'Login to Docker'
steps:
  - run:
      name: 'Login to Docker Registry'
      # As a side note, it's usually considered better practice to enter the token interactively, this way the token won't ever show up in your shell history or be visible on your screen
      command: |
        echo "$DIGITALOCEAN_ACCESS_TOKEN" | docker login --username codelabapp --password-stdin registry.digitalocean.com
