description: 'Restore Workspace'
steps:
  - checkout
  - attach_workspace:
      at: ~/
    - restore_cache:
        name: 'Restore node_modules Cache'
        keys:
          - node-modules-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}-
          - node-modules-cache-{{ checksum "pnpm-lock.yaml" }}
          - node-modules-cache-
      name: 'Restore NVM Cache'
      keys:
        - nvm-cache-{{ checksum ".nvmrc" }}
  # - restore_cache:
  #     name: 'Restore NX Cache'
  #     keys:
  #       # This is needed for e2e to run, but we add it here for simplicity
  #       - nx-cache-{{ checksum ".nx/cache/lockfile.hash" }}
  - install-pnpm
  - setup-env
