description: 'Restore Workspace'
steps:
  - checkout
  - setup-env
  # Attach `dist` folder
  - attach_workspace:
      at: ~/
  - run:
      name: 'Generate dist libs checksum for cache key'
      command: ~/project/scripts/circleci/generate-dist-checksum.sh
  - restore_cache:
      name: 'Restore node_modules Cache'
      keys:
        - node-modules-cache-{{ checksum "pnpm-lock.yaml" }}-{{ checksum "/tmp/dist-libs-checksum.txt" }}
        - node-modules-cache-{{ checksum "pnpm-lock.yaml" }}
        - node-modules-cache-
  - restore_cache:
      name: 'Restore NVM Cache'
      keys:
        - nvm-cache-{{ checksum ".nvmrc" }}
  - install-pnpm
