description: 'Restore Infra Workspace'
steps:
  - checkout
  - attach_workspace:
      at: ..
  - restore_cache:
      name: 'Restore Cache'
      keys:
        - pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
        - nvm-cache-{{ checksum ".nvmrc" }}
  - install-terraform
  - setup-env
