description: 'Save Nx << parameters.cache_name >> cache'
parameters:
  cache_name:
    type: string
    description: 'The name of the cache (e.g., lint, unit, integration, e2e, apps, libs)'
  extra_paths:
    type: string
    default: ''
    description: 'Additional paths to cache (optional)'
steps:
  - when:
      condition: << parameters.extra_paths >>
      steps:
        - save_cache:
            name: 'Save Nx << parameters.cache_name >> Cache'
            key: nx-<< parameters.cache_name >>-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}
            paths:
              - ${NX_CACHE_DIRECTORY}
              - << parameters.extra_paths >>
  - unless:
      condition: << parameters.extra_paths >>
      steps:
        - save_cache:
            name: 'Save Nx << parameters.cache_name >> Cache'
            key: nx-<< parameters.cache_name >>-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "pnpm-lock.yaml" }}
            paths:
              - ${NX_CACHE_DIRECTORY}
