description: 'Setup Neo4j'
steps:
  - run:
      name: Run Neo4j Memory Recommendations
      command: |
        neo4j-admin server memory-recommendation --docker
  - run:
      name: Enable CDC
      working_directory: .docker/cypher/scripts
      command: |
        ./enable-cdc.sh
  - run:
      name: Apply Neo4j Constraints
      working_directory: .docker/cypher/scripts
      command: |
        ./apply-constraints.sh
