module "auth0" {
  source = "./modules/auth0"

  AUTH0_ISSUER_BASE_URL    = var.AUTH0_ISSUER_BASE_URL
  NEXT_PUBLIC_BUILDER_HOST = var.NEXT_PUBLIC_BUILDER_HOST
  AUTH0_DOMAIN             = var.AUTH0_DOMAIN
  AUTH0_AUDIENCE           = var.AUTH0_AUDIENCE
  AUTH0_M2M_CLIENT_ID      = var.AUTH0_M2M_CLIENT_ID
  AUTH0_M2M_CLIENT_SECRET  = var.AUTH0_M2M_CLIENT_SECRET
  AUTH0_CYPRESS_PASSWORD   = var.AUTH0_CYPRESS_PASSWORD
}
