import type { IAtomRendererRecord } from '@codelab/frontend/abstract/domain'

import { dynamicLoader } from '@codelab/frontend/shared/utils'
import { IAtomType } from '@codelab/shared/abstract/core'

export const htmlAtoms: IAtomRendererRecord = {
  [IAtomType.HtmlA]: 'a',
  [IAtomType.HtmlAbbr]: 'abbr',
  [IAtomType.HtmlArea]: 'area',
  [IAtomType.HtmlArticle]: 'article',
  [IAtomType.HtmlAside]: 'aside',
  [IAtomType.HtmlAudio]: 'audio',
  [IAtomType.HtmlB]: 'b',
  [IAtomType.HtmlBase]: 'base',
  [IAtomType.HtmlBlockquote]: 'blockquote',
  [IAtomType.HtmlBr]: 'br',
  [IAtomType.HtmlButton]: 'button',
  [IAtomType.HtmlCanvas]: 'canvas',
  [IAtomType.HtmlCaption]: 'caption',
  [IAtomType.HtmlCite]: 'cite',
  [IAtomType.HtmlCode]: 'code',
  [IAtomType.HtmlData]: 'data',
  [IAtomType.HtmlDatalist]: 'datalist',
  [IAtomType.HtmlDetails]: 'details',
  [IAtomType.HtmlDfn]: 'dfn',
  [IAtomType.HtmlDialog]: 'dialog',
  [IAtomType.HtmlDiv]: 'div',
  [IAtomType.HtmlDl]: 'dl',
  [IAtomType.HtmlEm]: 'em',
  [IAtomType.HtmlEmbed]: 'embed',
  [IAtomType.HtmlFieldset]: 'fieldset',
  [IAtomType.HtmlFooter]: 'footer',
  [IAtomType.HtmlForm]: 'form',
  [IAtomType.HtmlH1]: 'h1',
  [IAtomType.HtmlH2]: 'h2',
  [IAtomType.HtmlH3]: 'h3',
  [IAtomType.HtmlH4]: 'h4',
  [IAtomType.HtmlH5]: 'h5',
  [IAtomType.HtmlH6]: 'h6',
  [IAtomType.HtmlHead]: 'head',
  [IAtomType.HtmlHeader]: 'header',
  [IAtomType.HtmlHr]: 'hr',
  [IAtomType.HtmlI]: 'i',
  [IAtomType.HtmlIframe]: 'iframe',
  [IAtomType.HtmlImg]: 'img',
  [IAtomType.HtmlInput]: 'input',
  [IAtomType.HtmlKbd]: 'kdb',
  [IAtomType.HtmlLabel]: 'label',
  [IAtomType.HtmlLegend]: 'legend',
  [IAtomType.HtmlLi]: 'li',
  [IAtomType.HtmlLink]: 'link',
  [IAtomType.HtmlMain]: 'main',
  [IAtomType.HtmlMap]: 'map',
  [IAtomType.HtmlMark]: 'mark',
  [IAtomType.HtmlMath]: 'math',
  [IAtomType.HtmlMeta]: 'meta',
  [IAtomType.HtmlMeter]: 'meter',
  [IAtomType.HtmlNav]: 'nav',
  [IAtomType.HtmlNoscript]: 'noscript',
  [IAtomType.HtmlObject]: 'object',
  [IAtomType.HtmlOl]: 'ol',
  [IAtomType.HtmlOptgroup]: 'optgroup',
  [IAtomType.HtmlOption]: 'option',
  [IAtomType.HtmlOutput]: 'output',
  [IAtomType.HtmlP]: 'p',
  [IAtomType.HtmlPicture]: 'picture',
  [IAtomType.HtmlPre]: 'pre',
  [IAtomType.HtmlProgress]: 'progress',
  [IAtomType.HtmlQ]: 'q',
  [IAtomType.HtmlRuby]: 'ruby',
  [IAtomType.HtmlS]: 's',
  [IAtomType.HtmlSamp]: 'samp',
  [IAtomType.HtmlScript]: dynamicLoader(() =>
    import(
      '@codelab/frontend-application-atom/components/custom/codelab-script'
    ).then((mod) => mod.CodelabScript),
  ),
  [IAtomType.HtmlSection]: 'section',
  [IAtomType.HtmlSelect]: 'select',
  [IAtomType.HtmlSmall]: 'small',
  [IAtomType.HtmlSource]: 'source',
  [IAtomType.HtmlSpan]: 'span',
  [IAtomType.HtmlStrong]: 'strong',
  [IAtomType.HtmlStyle]: 'style',
  [IAtomType.HtmlSub]: 'sub',
  [IAtomType.HtmlSup]: 'sup',
  [IAtomType.HtmlTable]: 'table',
  // [IAtomType.HtmlCol]: 'col',
  [IAtomType.HtmlTd]: 'td',
  [IAtomType.HtmlTemplate]: 'template',
  [IAtomType.HtmlTextarea]: 'textarea',
  [IAtomType.HtmlTime]: 'time',
  [IAtomType.HtmlTitle]: 'title',
  [IAtomType.HtmlTr]: 'tr',
  [IAtomType.HtmlTrack]: 'track',
  [IAtomType.HtmlUl]: 'ul',
  [IAtomType.HtmlVideo]: 'video',
}
