commands:
  build-repo:
    description: Build Repo
    steps:
      - nx/set-shas:
          main-branch-name: master
      - run: echo $CIRCLE_API_TOKEN
      - run:
          command: pnpm nx affected --target=build --parallel=3 -c ci --nx-bail
  clear-jest-cache:
    description: Clear Jest Spec
    steps:
      - run:
          command: |
            pnpm jest --clearCache
  install-nvm:
    steps:
      - restore_cache:
          keys:
            - nvm-cache-{{ checksum ".nvmrc" }}
          name: Restore NVM Cache
      - run:
          command: source ~/project/.circleci/config/install-nvm.sh
          name: Install NVM
      - save_cache:
          key: nvm-cache-{{ checksum ".nvmrc" }}
          name: Save NVM Cache
          paths:
            - ~/.nvm
      - run:
          command: |
            nvm install 18.18.0
            nvm alias default 18.18.0
            node -v
          name: Set Node Version
  install-packages:
    steps:
      - restore_cache:
          keys:
            - pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
            - pnpm-cache
          name: Restore pnpm Cache
      - run:
          command: pnpm install --frozen-lockfile --verbose
          environment:
            PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
            PUPPETEER_SKIP_DOWNLOAD: true
          name: Install NPM Packages
      - save_cache:
          key: pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
          name: Save pnpm Cache
          paths:
            - ~/.pnpm-store
      - save_cache:
          key: node_modules-cache-{{ checksum "pnpm-lock.yaml" }}
          name: Save node_modules Cache
          paths:
            - ~/project/node_modules
  install-packer:
    description: Install Packer
    steps:
      - run:
          command: |
            set -x

            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

            sudo apt-get update && sudo apt-get install packer
          name: Install Packer
  install-pnpm:
    steps:
      - run:
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@9.1.1 --activate
            pnpm config set store-dir ~/.pnpm-store
          name: Install pnpm package manager
  install-terraform:
    description: Install Terraform
    steps:
      - run:
          command: |
            set -x

            sudo apt-get update && sudo apt-get install -y gnupg software-properties-common

            apt list upgrade

            wget -O- https://apt.releases.hashicorp.com/gpg | \
            gpg --dearmor | \
            sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
            sudo tee /etc/apt/sources.list.d/hashicorp.list

            gpg --no-default-keyring \
            --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
            --fingerprint

            sudo apt update
            sudo apt install terraform=1.7.0-*
          name: Install Terraform
  login-docker:
    description: Login to Docker
    steps:
      - run:
          command: |
            echo "$DIGITALOCEAN_ACCESS_TOKEN" | docker login --username codelabapp --password-stdin registry.digitalocean.com
          name: Login to Docker Registry
  restore-infra-workspace:
    description: Restore Infra Workspace
    steps:
      - restore-workspace
      - install-terraform
  restore-workspace:
    description: Restore Workspace
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - node_modules-cache-{{ checksum "pnpm-lock.yaml" }}
          name: Restore node_modules Cache
      - restore_cache:
          keys:
            - nvm-cache-{{ checksum ".nvmrc" }}
          name: Restore NVM Cache
      - install-pnpm
      - setup-env
  setup-env:
    description: Setup Env
    steps:
      - run:
          command: source ~/project/.circleci/config/env.sh
          name: Setup Env
executors:
  docker-node:
    docker:
      - image: cimg/node:18.18.0-browsers
  docker-node-neo4j:
    docker:
      - image: cimg/node:18.18.0-browsers
        name: 127.0.0.1
      - command:
          - neo4j
          - start
        environment:
          NEO4J_AUTH: neo4j/password
          NEO4J_PLUGINS: '["apoc"]'
        image: neo4j:5.11.0
  machine-ubuntu:
    machine:
      image: ubuntu-2004:2022.04.1
  playwright:
    docker:
      - image: mcr.microsoft.com/playwright:v1.46.0-jammy
  terraform:
    docker:
      - image: hashicorp/terraform:1.7.0
    environment:
      TF_WORKSPACE: prod
jobs:
  apply:
    executor: docker-node
    steps:
      - restore-infra-workspace
      - run:
          command: pnpm cli terraform --stage prod init
          name: Terraform Init
      - run:
          command: pnpm cli terraform --stage prod apply
          name: Terraform Apply
  codegen:
    executor: docker-node-neo4j
    parameters:
      resource_class:
        type: string
    resource_class: << parameters.resource_class >>
    steps:
      - restore-workspace
      - run:
          command: pnpm cli tasks graphql-codegen --stage ci
          name: Check GraphQL Codegen
      - run:
          command: pnpm cli tasks workspace-codegen --stage ci
          name: Check Generate Workspace
  docker-api:
    executor: docker-node
    resource_class: medium
    steps:
      - restore-workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: (./scripts/docker/prod/build-api.sh)
          name: Build api Docker image
      - run:
          command: docker compose --verbose -f .docker/prod/build.docker-compose.yaml push api
          name: Push Docker Image
  docker-landing:
    executor: docker-node
    resource_class: medium
    steps:
      - restore-workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: (./scripts/docker/prod/build-landing.sh)
          name: Build landing Docker image
      - run:
          command: docker compose --verbose -f .docker/prod/build.docker-compose.yaml push landing
          name: Push Docker Image
  docker-sites:
    executor: docker-node
    resource_class: large
    steps:
      - restore-workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: (./scripts/docker/prod/build-sites.sh)
          name: Build sites Docker image
      - run:
          command: docker compose --verbose -f .docker/prod/build.docker-compose.yaml push sites
          name: Push Docker Image
  docker-web:
    executor: docker-node
    resource_class: medium
    steps:
      - restore-workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: (./scripts/docker/prod/build-web.sh)
          name: Build web Docker image
      - run:
          command: docker compose --verbose -f .docker/prod/build.docker-compose.yaml push web
          name: Push Docker Image
  e2e:
    environment:
      NODE_OPTIONS: --max-old-space-size=<< parameters.max_old_space_size >>
    executor: docker-node-neo4j
    parameters:
      max_old_space_size:
        type: integer
      resource_class:
        type: string
    resource_class: << parameters.resource_class >>
    steps:
      - restore-workspace
      - run: pnpm npx playwright install-deps
      - run:
          command: pnpm nx e2e web-e2e -c ci
          name: Run E2E Tests
      - store_artifacts:
          destination: playwright-report
          path: ~/project/dist/.playwright/apps/web-e2e/playwright-report
      - store_test_results:
          path: ~/project/dist/.playwright/apps/web-e2e/test-output
  integration:
    executor: docker-node-neo4j
    parameters:
      resource_class:
        type: string
    resource_class: << parameters.resource_class >>
    steps:
      - restore-workspace
      - run:
          command: pnpm cli tasks int --stage ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./tmp/reports/test-integration
          name: Run Integration Tests
          no_output_timeout: 20m
      - store_test_results:
          path: ./tmp/reports/test-integration
  lint:
    environment:
      CIRCLE_BASE_REVISION: << pipeline.git.base_revision >>
      CIRCLE_REVISION: << pipeline.git.revision >>
    executor: docker-node-neo4j
    parameters:
      resource_class:
        type: string
    resource_class: << parameters.resource_class >>
    steps:
      - restore-workspace
      - run:
          command: pnpm cli tasks lint --stage ci
          name: Run Lint on Repository
      - run:
          command: pnpm cli tasks commitlint --stage ci
          name: Commitlint
      - store_test_results:
          path: ./tmp/reports/lint
  notify-failure:
    executor: machine-ubuntu
    resource_class: small
    steps:
      - swissknife/wait_for_job:
          job-name: install-and-build-workspace,lint,unit,e2e,codegen
      - slack/notify:
          channel: $SLACK_CHANNEL_UPDATE
          event: fail
          template: basic_fail_1
  notify-success:
    executor: docker-node
    parameters:
      resource_class:
        type: string
    resource_class: << parameters.resource_class >>
    steps:
      - slack/notify:
          channel: $SLACK_CHANNEL_UPDATE
          custom: |
            {
            	"text": "CircleCI job succeeded!",
            	"blocks": [
            		{
            			"type": "header",
            			"text": {
            				"type": "plain_text",
            				"text": "Job Succeeded. :white_check_mark:",
            				"emoji": true
            			}
            		},
            		{
            			"type": "section",
            			"fields": [
            				{
            					"type": "mrkdwn",
            					"text": "*Job*: ${CIRCLE_JOB}"
            				}
            			]
            		},
            		{
            			"type": "section",
            			"fields": [
            				{
            					"type": "mrkdwn",
            					"text": "*Project*:\n $CIRCLE_PROJECT_REPONAME"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*Branch*:\n $CIRCLE_BRANCH"
                            },
                            {
            					"type": "mrkdwn",
            					"text": "*Commit*:\n $CIRCLE_SHA1"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*Author*:\n $CIRCLE_USERNAME"
            				}
            			],
            			"accessory": {
            				"type": "image",
            				"image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
            				"alt_text": "CircleCI logo"
            			}
            		},
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Mentions*:\n $SLACK_PARAM_MENTIONS"
                    }
                  ]
                },
            		{
            			"type": "actions",
            			"elements": [
            				{
            					"type": "button",
            					"text": {
            						"type": "plain_text",
            						"text": "View Job"
            					},
            					"url": "${CIRCLE_BUILD_URL}"
            				}
            			]
            		}
            	]
            }
          event: pass
  packer-image:
    executor: docker-node
    resource_class: medium
    steps:
      - restore-workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: (./scripts/docker/prod/build-landing.sh)
          name: Build landing Docker image
      - run:
          command: docker compose --verbose -f .docker/prod/build.docker-compose.yaml push landing
          name: Push Docker Image
  plan:
    executor: docker-node
    steps:
      - restore-infra-workspace
      - run:
          command: |
            echo "credentials \"app.terraform.io\" {token = \"$TERRAFORM_TOKEN\"}" >> $HOME/.terraformrc
          name: Create .terraformrc file locally
      - run: terraform --version
      - run:
          command: terraform -chdir=infra/terraform fmt
          name: Terraform Format
      - run:
          command: pnpm cli terraform --stage prod init
          name: Terraform Init
      - run:
          command: pnpm cli terraform --stage prod validate
          name: Terraform Validate
      - run:
          command: pnpm cli terraform --stage prod plan
          name: Terraform Plan
      - persist_to_workspace:
          paths:
            - .terraformrc
            - project/terraform/.terraform
          root: ~/
  setup-infra-workspace:
    executor: docker-node
    resource_class: large
    steps:
      - install-terraform
      - login-docker
      - persist_to_workspace:
          paths:
            - .docker/config.json
          root: ~/
  setup-workspace:
    environment:
      NODE_OPTIONS: --max-old-space-size=<< parameters.max_old_space_size >>
    executor: docker-node
    parameters:
      max_old_space_size:
        type: integer
      resource_class:
        type: string
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - setup-env
      - install-nvm
      - install-pnpm
      - install-packages
      - build-repo
      - persist_to_workspace:
          paths:
            - project/dist/apps/cli
            - project/dist/apps/web
          root: ~/
  unit:
    executor: docker-node
    parameters:
      resource_class:
        type: string
    resource_class: << parameters.resource_class >>
    steps:
      - restore-workspace
      - run:
          command: pnpm cli tasks unit --stage ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./tmp/reports/test-unit
          name: Run Unit Tests
      - store_test_results:
          path: ./tmp/reports/test-unit
orbs:
  node: circleci/node@5.1.0
  nx: nrwl/nx@1.6.2
  queue: eddiewebb/queue@2.2.1
  slack: circleci/slack@4.12.5
  swissknife: roopakv/swissknife@0.69.0
  terraform: circleci/terraform@3.2.1
version: 2.1
workflows:
  app:
    jobs:
      - setup-workspace:
          filters:
            branches:
              only:
                - master
          max_old_space_size: 6144
          resource_class: large
      - hold-deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - setup-workspace
          type: approval
      - setup-infra-workspace:
          filters:
            branches:
              only:
                - master
          requires:
            - hold-deploy
      - docker-web:
          context:
            - prod
          filters:
            branches:
              only:
                - master
          requires:
            - setup-infra-workspace
      - docker-api:
          context:
            - prod
          filters:
            branches:
              only:
                - master
          requires:
            - setup-infra-workspace
      - docker-sites:
          context:
            - prod
          filters:
            branches:
              only:
                - master
          requires:
            - setup-infra-workspace
      - docker-landing:
          context:
            - prod
          filters:
            branches:
              only:
                - master
          requires:
            - setup-infra-workspace
      - plan:
          filters:
            branches:
              only:
                - master
          requires:
            - docker-web
            - docker-api
            - docker-sites
            - docker-landing
      - hold-apply:
          filters:
            branches:
              only:
                - master
          requires:
            - plan
          type: approval
      - apply:
          filters:
            branches:
              only:
                - master
          requires:
            - hold-apply
  app-pr:
    jobs:
      - setup-workspace:
          context:
            - build
          filters:
            branches:
              ignore:
                - master
                - staging
          max_old_space_size: 6144
          resource_class: large
      - lint:
          filters:
            branches:
              ignore:
                - master
                - staging
          requires:
            - setup-workspace
          resource_class: large
      - codegen:
          filters:
            branches:
              ignore:
                - master
                - staging
          requires:
            - setup-workspace
          resource_class: medium
      - unit:
          filters:
            branches:
              ignore:
                - master
                - staging
          requires:
            - setup-workspace
          resource_class: large
      - integration:
          filters:
            branches:
              ignore:
                - master
                - staging
          requires:
            - setup-workspace
          resource_class: large
      - e2e:
          filters:
            branches:
              ignore:
                - master
                - staging
          max_old_space_size: 4096
          requires:
            - setup-workspace
          resource_class: large
      - notify-success:
          filters:
            branches:
              ignore:
                - master
                - staging
          requires:
            - lint
            - codegen
            - unit
            - integration
            - e2e
          resource_class: medium
  infra-pr:
    jobs:
      - setup-workspace:
          filters:
            branches:
              only:
                - staging
          max_old_space_size: 6144
          resource_class: large
      - setup-infra-workspace:
          filters:
            branches:
              only:
                - staging
          requires:
            - setup-workspace
      - docker-web:
          context:
            - prod
          filters:
            branches:
              only:
                - staging
          requires:
            - setup-infra-workspace
      - docker-api:
          context:
            - prod
          filters:
            branches:
              only:
                - staging
          requires:
            - setup-infra-workspace
      - docker-sites:
          context:
            - prod
          filters:
            branches:
              only:
                - staging
          requires:
            - setup-infra-workspace
      - docker-landing:
          context:
            - prod
          filters:
            branches:
              only:
                - staging
          requires:
            - setup-infra-workspace
      - plan:
          filters:
            branches:
              only:
                - staging
          requires:
            - docker-web
            - docker-api
            - docker-sites
            - docker-landing
      - hold-apply:
          filters:
            branches:
              only:
                - staging
          requires:
            - plan
          type: approval
      - apply:
          filters:
            branches:
              only:
                - staging
          requires:
            - hold-apply
working_directory: ~/project
