version: '3.8'
services:
  sites:
    image: registry.digitalocean.com/codelabapp/sites:${docker_tag_version}
    container_name: codelab-sites
    restart: unless-stopped
    ports:
      - '80:3000'
    environment:
      - NEXT_PUBLIC_WEB_HOST=${next_public_web_host}
      - NEXT_PUBLIC_API_PORT=${next_public_api_port}
      - NEXT_PUBLIC_API_HOSTNAME=${next_public_api_hostname}
