export enum EntityType {
  Action = 'Action',
  Admin = 'Admin',
  App = 'App',
  Atom = 'Atom',
  AuthGuard = 'AuthGuard',
  Builder = 'Builder',
  Component = 'Component',
  Domain = 'Domain',
  Element = 'Element',
  Field = 'Field',
  Page = 'Page',
  Pagination = 'Pagination',
  Prop = 'Prop',
  Redirect = 'Redirect',
  Resource = 'Resource',
  Tag = 'Tag',
  Type = 'Type',
  User = 'User',
}
