import type { UiDataRecord } from './ui-data'

export interface UiData {
  key: string
  label: string
}

export enum UiKey {
  // App
  ImportAppToolbarItem = 'ImportAppToolbarItem',
  CreateAppToolbarItem = 'CreateAppToolbarItem',
  BuildAppModal = 'BuildAppModal',
  CreateAppModal = 'CreateAppModal',
  DeleteAppModal = 'DeleteAppModal',
  UpdateAppModal = 'UpdateAppModal',
  BuildAppToolbarItem = 'BuildAppToolbarItem',
  CreateAppForm = 'CreateAppForm',

  // Page
  CreatePageForm = 'CreatePageForm',
  CreatePagePopover = 'CreatePagePopover',
  CreatePageToolbarItem = 'CreatePageToolbarItem',
  CancelCreatePageToolbarItem = 'CancelCreatePageToolbarItem',
  DeletePageModal = 'DeletePageModal',
  DeletePageToolbarItem = 'DeletePageToolbarItem',
  UpdatePageForm = 'UpdatePageForm',
  UpdatePageToolbarItem = 'UpdatePageToolbarItem',
  UpdatePagePopover = 'UpdatePagePopover',
  CancelUpdatePageToolbarItem = 'CancelUpdatePageToolbarItem',
  PageSidebar = 'PageSidebar',
  // Atom
  CreateAtomPopover = 'CreateAtomPopover',
  CreateAtomToolbarItem = 'CreateAtomToolbarItem',
  CancelCreateAtomToolbarItem = 'CancelCreateAtomToolbarItem',
  CreateAtomModal = 'CreateAtomModal',
  CreateAtomForm = 'CreateAtomForm',
  DeleteAtomModal = 'DeleteAtomModal',
  DeleteAtomsModal = 'DeleteAtomsModal',
  UpdateAtomModal = 'UpdateAtomModal',
  UpdateAtomForm = 'UpdateAtomForm',
  DeleteAtomsToolbarItem = 'DeleteAtomsToolbarItem',
  AtomSidebar = 'AtomSidebar',
  // Element
  CreateElementToolbarItem = 'CreateElementToolbarItem',
  CreateElementPopover = 'CreateElementPopover',
  CancelCreateElementToolbarItem = 'CancelCreateElementToolbarItem',
  MoveElementForm = 'MoveElementForm',
  UpdateElementForm = 'UpdateElementForm',
  // Component
  CreateComponentToolbarItem = 'CreateComponentToolbarItem',
  CreateComponentPopover = 'CreateComponentPopover',
  ComponentSidebar = 'ComponentSidebar',
  ImportComponentToolbarItem = 'ImportComponentToolbarItem',
  CreateComponentForm = 'CreateComponentForm',
  CancelCreateComponentToolbarItem = 'CancelCreateComponentToolbarItem',
  DeleteComponentModal = 'DeleteComponentModal',
  UpdateComponentModal = 'UpdateComponentModal',
  UpdateComponentForm = 'UpdateComponentForm',
  // Action
  CreateActionToolbarItem = 'CreateActionToolbarItem',
  CreateActionPopover = 'CreateActionPopover',
  CreateActionForm = 'CreateActionForm',
  CreateActionModal = 'CreateActionModal',
  CancelCreateActionToolbarItem = 'CancelCreateActionToolbarItem',
  DeleteActionModal = 'DeleteActionModal',
  UpdateActionPopover = 'UpdateActionPopover',
  UpdateActionToolbarItem = 'UpdateActionToolbarItem',
  DeleteActionToolbarItem = 'DeleteActionToolbarItem',
  UpdateActionForm = 'UpdateActionForm',
  UpdateActionModal = 'UpdateActionModal',
  CancelUpdateActionToolbarItem = 'CancelUpdateActionToolbarItem',

  // Field
  CreateFieldPopover = 'CreateFieldPopover',
  CreateFieldToolbarItem = 'CreateFieldToolbarItem',
  CreateFieldForm = 'CreateFieldForm',
  CreateFieldModal = 'CreateFieldModal',
  CancelCreateFieldToolbarItem = 'CancelCreateFieldToolbarItem',
  DeleteFieldModal = 'DeleteFieldModal',
  UpdateFieldPopover = 'UpdateFieldPopover',
  UpdateFieldToolbarItem = 'UpdateFieldToolbarItem',
  DeleteFieldToolbarItem = 'DeleteFieldToolbarItem',
  UpdateFieldModal = 'UpdateFieldModal',
  UpdateFieldForm = 'UpdateFieldForm',
  CancelUpdateFieldToolbarItem = 'CancelUpdateFieldToolbarItem',
  SelectDefaultValueFieldForm = 'SelectDefaultValueFieldForm',
  SelectUnionTypeValueFieldForm = 'SelectUnionTypeValueFieldForm',
  // Type
  CreateTypeModal = 'CreateTypeModal',
  CreateTypeForm = 'CreateTypeForm',
  CreateTypePopover = 'CreateTypePopover',
  CreateTypeToolbarItem = 'CreateTypeToolbarItem',
  CancelCreateTypeToolbarItem = 'CancelCreateTypeToolbarItem',
  DeleteTypeModal = 'DeleteTypeModal',
  DeleteTypeToolbarItem = 'DeleteTypeToolbarItem',
  UpdateTypeForm = 'UpdateTypeForm',
  UpdateTypeModal = 'UpdateTypeModal',
  TypeSidebar = 'TypeSidebar',
  // Resource
  CreateResourceModal = 'CreateResourceModal',
  CreateResourceForm = 'CreateResourceForm',
  CreateResourcePopover = 'CreateResourcePopover',
  CreateResourceToolbarItem = 'CreateResourceToolbarItem',
  CancelCreateResourceToolbarItem = 'CancelCreateResourceToolbarItem',
  DeleteResourceModal = 'DeleteResourceModal',
  DeleteResourceToolbarItem = 'DeleteResourceToolbarItem',
  UpdateResourceModal = 'UpdateResourceModal',
  UpdateResourceForm = 'UpdateResourceForm',
  ResourceSidebar = 'ResourceSidebar',
  // Redirect
  UpdateRedirectToolbarItem = 'UpdateRedirectToolbarItem',
  CreateRedirectToolbarItem = 'CreateRedirectToolbarItem',
  UpdateRedirectPopover = 'UpdateRedirectPopover',
  CreateRedirectPopover = 'CreateRedirectPopover',
  CreateRedirectForm = 'CreateRedirectForm',
  CancelCreateRedirectToolbarItem = 'CancelCreateRedirectToolbarItem',
  DeleteRedirectModal = 'DeleteRedirectModal',
  UpdateRedirectForm = 'UpdateRedirectForm',
  CancelUpdateRedirectToolbarItem = 'CancelUpdateRedirectToolbarItem',
  // AuthGuard
  CreateAuthGuardModal = 'CreateAuthGuardModal',
  CreateAuthGuardForm = 'CreateAuthGuardForm',
  CreateAuthGuardPopover = 'CreateAuthGuardPopover',
  DeleteAuthGuardModal = 'DeleteAuthGuardModal',
  CreateAuthGuardToolbarItem = 'CreateAuthGuardToolbarItem',
  CancelCreateAuthGuardToolbarItem = 'CancelCreateAuthGuardToolbarItem',
  DeleteAuthGuardToolbarItem = 'DeleteAuthGuardToolbarItem',
  UpdateAuthGuardModal = 'UpdateAuthGuardModal',
  UpdateAuthGuardForm = 'UpdateAuthGuardForm',
  AuthGuardSidebar = 'AuthGuardSidebar',
  // Tag
  CreateTagModal = 'CreateTagModal',
  CreateTagForm = 'CreateTagForm',
  CreateTagPopover = 'CreateTagPopover',
  CreateTagToolbarItem = 'CreateTagToolbarItem',
  CancelCreateTagToolbarItem = 'CancelCreateTagToolbarItem',
  DeleteTagModal = 'DeleteTagModal',
  DeleteTagToolbarItem = 'DeleteTagToolbarItem',
  UpdateTagForm = 'UpdateTagForm',
  UpdateTagModal = 'UpdateTagModal',
  TagSidebar = 'TagSidebar',
  // Admin
  ExportAdminDataModal = 'ExportAdminDataModal',
  ImportAdminDataModal = 'ImportAdminDataModal',
  // User
  SignOutUserToolbarItem = 'SignOutUserToolbarItem',
  // Builder
  BuilderSidebar = 'BuilderSidebar',
  OpenBuilderBuilderToolbarItem = 'OpenBuilderBuilderToolbarItem',
  OpenPreviewBuilderToolbarItem = 'OpenPreviewBuilderToolbarItem',
  // Domain
  CreateDomainToolbarItem = 'CreateDomainToolbarItem',
  CreateDomainModal = 'CreateDomainModal',
  DeleteDomainModal = 'DeleteDomainModal',
  UpdateDomainModal = 'UpdateDomainModal',
  // Lambda
  CreateLambdaToolbarItem = 'CreateLambdaToolbarItem',
  // Pagination
  PageSizePaginationToolbarItem = 'PageSizePaginationToolbarItem',
  PreviousPagePaginationToolbarItem = 'PreviousPagePaginationToolbarItem',
  NextPagePaginationToolbarItem = 'NextPagePaginationToolbarItem',
  SearchPaginationToolbarItem = 'SearchPaginationToolbarItem',
  CurrentPagePaginationToolbarItem = 'CurrentPagePaginationToolbarItem',
  SearchPaginationToobarItem = 'SearchPaginationToobarItem',
  CancelCreateTagToolabarItem = 'CancelCreateTagToolabarItem',
}

export type UiKeys = (typeof UiDataRecord)[keyof typeof UiDataRecord]['key']
