---
- name: Provision Consul server image
  hosts: default
  become: yes

  pre_tasks:
    # Wait for cloud-init to complete to avoid apt lock conflicts
    - name: Wait for cloud-init to complete
      command: cloud-init status --wait
      failed_when: false
      changed_when: false

    # Fix any interrupted package installs
    - name: Configure dpkg
      command: dpkg --configure -a
      failed_when: false
      changed_when: false

  tasks:
    # Add consul-server.hcl for server nodes
    - name: Copy Consul server configuration
      copy:
        src: '../../modules/consul-server/consul-server.hcl'
        dest: /etc/consul.d/consul-server.hcl
        owner: consul
        group: consul
        mode: '0640'

    # Fix permissions for Consul configuration files
    - name: Set Consul configuration permissions
      file:
        path: /etc/consul.d
        owner: consul
        group: consul
        recurse: yes

    # Clean up temporary files
    - name: Clean temporary files
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - /tmp/*
        - /var/tmp/*
      failed_when: false

    # Trim filesystem to minimize snapshot size
    - name: Trim filesystem
      command: fstrim -av
