---
- name: Provision Consul server image
  hosts: default
  become: yes

  pre_tasks:
    # Wait for cloud-init to complete to avoid apt lock conflicts
    - name: Wait for cloud-init to complete
      command: cloud-init status --wait
      failed_when: false
      changed_when: false

    # Fix any interrupted package installs
    - name: Configure dpkg
      command: dpkg --configure -a
      failed_when: false
      changed_when: false

  tasks:
    # Add consul-server.hcl for server nodes
    - name: Copy Consul server configuration
      copy:
        src: '../../modules/consul-server/consul-server.hcl'
        dest: /etc/consul.d/consul-server.hcl
        owner: consul
        group: consul
        mode: '0640'

    # Re-enable Consul service for server nodes (was disabled in base image)
    # The base image disables Consul to prevent it from running during build
    # But consul-server needs it enabled so it starts automatically on boot
    # We keep it stopped during build but enable it for systemd to start on boot
    - name: Enable Consul service for server
      systemd:
        name: consul
        state: stopped # Don't run during Packer build
        enabled: yes # But enable for auto-start on boot

    # Fix permissions for Consul configuration files
    - name: Set Consul configuration permissions
      file:
        path: /etc/consul.d
        owner: consul
        group: consul
        recurse: yes

    # Run complete cleanup including machine-id truncation
    - name: Complete service image cleanup
      include_tasks: ../base/tasks/cleanup.yml
