export enum FormNames {
  CreateField = 'Create Field',
  UpdateField = 'Update Field',
  CreateElement = 'Create Element',
  UpdateElement = 'Update Element',
  CreateAction = 'Create Action',
  UpdateAction = 'Update Action',
  CreateComponent = 'Create Component',
  UpdateComponent = 'Update Component',
  CreatePage = 'Create Page',
  UpdatePage = 'Update Page',
  CreateType = 'Create Type',
  UpdateType = 'Update Type',
  CreateAtom = 'Create Atom',
  UpdateAtom = 'Update Atom',
  CreateTag = 'Create Tag',
  UpdateTag = 'Update Tag',
}
