---
- name: Provision Landing service image
  hosts: default
  become: yes
  vars:
    digitalocean_api_token: '{{ digitalocean_api_token }}'
    region: "{{ region | default('sgp1') }}"

  pre_tasks:
    # Skip cloud-init wait in Packer builds to save ~5 minutes
    # Cloud-init isn't needed during image creation and should run on first boot in production

    # Fix any interrupted package installs
    - name: Configure dpkg
      command: dpkg --configure -a
      failed_when: false
      changed_when: false

  tasks:
    # Landing-specific Docker Compose template
    - name: Copy Landing Docker Compose template
      copy:
        src: 'docker-compose.ctmpl'
        dest: /etc/consul-template/docker-compose.ctmpl

    # Create caddy directory
    - name: Create caddy directory
      file:
        path: /opt/caddy
        state: directory
        mode: '0755'

    # Landing-specific static Caddyfile
    - name: Copy Landing Caddyfile
      copy:
        src: 'Caddyfile'
        dest: /opt/caddy/Caddyfile
        mode: '0644'

    # Landing-specific consul-template configuration
    - name: Copy Landing consul-template configuration
      copy:
        src: 'docker.consul-template.hcl'
        dest: /etc/consul-template.d/docker.hcl
        owner: root
        group: root
        mode: '0644'

    # Add consul-client.hcl for Landing service
    - name: Configure Consul client
      copy:
        content: |
          # Consul Client Configuration
          # This file configures Consul to run as a client (not a server)

          # Bind to localhost only for client nodes (security best practice)
          # This prevents external access to the Consul API on client nodes
          client_addr = "127.0.0.1"

          # Automatically join the Consul cluster using DigitalOcean tags
          retry_join = ["provider=digitalocean region={{ region }} tag_name=consul-server api_token={{ digitalocean_api_token }}"]

          # Retry joining forever (useful for auto-scaling scenarios)
          retry_interval = "30s"
          retry_max = 0
        dest: /etc/consul.d/consul-client.hcl
        owner: consul
        group: consul
        mode: '0640'

    # Fix permissions for Consul configuration files
    - name: Set Consul configuration permissions
      file:
        path: /etc/consul.d
        owner: consul
        group: consul
        recurse: yes

    # Setup Docker registry authentication
    - name: Authenticate with DigitalOcean registry
      command: doctl registry login

    # Clean up temporary files
    - name: Clean temporary files
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - /tmp/*
        - /var/tmp/*
      failed_when: false

    # Trim filesystem to minimize snapshot size
    - name: Trim filesystem
      command: fstrim -av
