---
- name: Provision Landing service image
  hosts: default
  become: yes
  vars:
    digitalocean_api_token: '{{ digitalocean_api_token }}'
    region: "{{ region | default('sgp1') }}"

  pre_tasks:
    # Wait for cloud-init to complete to avoid apt lock conflicts
    - name: Wait for cloud-init to complete
      command: cloud-init status --wait
      failed_when: false
      changed_when: false

    # Fix any interrupted package installs
    - name: Configure dpkg
      command: dpkg --configure -a
      failed_when: false
      changed_when: false

  tasks:
    # Landing-specific Docker Compose template
    - name: Copy Landing Docker Compose template
      copy:
        src: 'docker-compose.ctmpl'
        dest: /etc/consul-template/docker-compose.ctmpl

    # Create caddy directory
    - name: Create caddy directory
      file:
        path: /opt/caddy
        state: directory
        mode: '0755'

    # Landing-specific static Caddyfile
    - name: Copy Landing Caddyfile
      copy:
        src: 'Caddyfile'
        dest: /opt/caddy/Caddyfile
        mode: '0644'

    # Landing-specific consul-template configuration
    - name: Copy Landing consul-template configuration
      copy:
        src: 'docker.consul-template.hcl'
        dest: /etc/consul-template.d/docker.hcl
        owner: root
        group: root
        mode: '0644'

    # Add consul-client.hcl for Landing service
    - name: Configure Consul client
      template:
        src: '../../modules/consul-client/consul-client.hcl.tpl'
        dest: /etc/consul.d/consul-client.hcl
        owner: consul
        group: consul
        mode: '0640'
      vars:
        digitalocean_api_token: '{{ digitalocean_api_token }}'
        region: '{{ region }}'

    # Fix permissions for Consul configuration files
    - name: Set Consul configuration permissions
      file:
        path: /etc/consul.d
        owner: consul
        group: consul
        recurse: yes

    # Run complete cleanup including machine-id truncation
    - name: Complete service image cleanup
      include_tasks: ../base/tasks/cleanup.yml

    # Verify system is ready for snapshot
    - name: Verify system is ready for snapshot
      include_tasks: ../base/tasks/verify-snapshot.yml
