// Assuming your custom plugin is correctly installed/linked
// You might need to adjust the import path if it's local
import codelabPlugin from '@codelab/eslint-plugin'

// GENERATED BY CURSOR
export default [
  {
    files: ['**/*.{ts,tsx}'], // Target TypeScript/TSX files
    plugins: {
      '@codelab': codelabPlugin, // Register the custom plugin
    },
    rules: {
      // Example: Enable a custom rule (adjust as needed)
      // "@codelab/domain-layer-constraint": "error",
      '@codelab/ant-design-icon-import': 'error',
      '@codelab/typebox-schema-naming': 'error',
    },
  },
]
