import unusedImportsPlugin from 'eslint-plugin-unused-imports'
import tsPlugin from '@typescript-eslint/eslint-plugin'
import preferArrowPlugin from 'eslint-plugin-prefer-arrow'
import nxPlugin from '@nx/eslint-plugin'

// GENERATED BY CURSOR
export default [
  {
    files: ['**/*.gen.ts', '**/*.gen.tsx'], // Target generated files
    // Ensure the plugins are available in the overall ESLint configuration
    plugins: {
      'unused-imports': unusedImportsPlugin,
      '@typescript-eslint': tsPlugin,
      'prefer-arrow': preferArrowPlugin,
      '@nx': nxPlugin,
    },
    rules: {
      // Rules specific to generated files
      'unused-imports/no-unused-imports-ts': 'error', // Ensure no unused imports in generated code
      'func-style': 'off', // Allow different function styles
      '@typescript-eslint/no-explicit-any': 'off', // Allow explicit 'any'
      '@typescript-eslint/member-ordering': 'off', // Disable strict member ordering
      '@typescript-eslint/consistent-type-definitions': 'off', // Allow flexible type definitions
      '@typescript-eslint/naming-convention': 'off', // Disable strict naming conventions
      'prefer-arrow/prefer-arrow-functions': 'off', // Allow non-arrow functions
      '@nx/enforce-module-boundaries': 'off', // Disable module boundary checks
    },
  },
]
