// GENERATED BY CURSOR
export default [
  {
    files: ['**/*.gen.ts', '**/*.gen.tsx'], // Target generated files
    rules: {
      // Rules specific to generated files
      'unused-imports/no-unused-imports-ts': 'error', // Ensure no unused imports in generated code
      'func-style': 'off', // Allow different function styles
      '@typescript-eslint/no-explicit-any': 'off', // Allow explicit 'any'
      '@typescript-eslint/member-ordering': 'off', // Disable strict member ordering
      '@typescript-eslint/consistent-type-definitions': 'off', // Allow flexible type definitions
      '@typescript-eslint/naming-convention': 'off', // Disable strict naming conventions
      'prefer-arrow/prefer-arrow-functions': 'off', // Allow non-arrow functions
      '@nx/enforce-module-boundaries': 'off', // Disable module boundary checks
    },
  },
]
