import perfectionistPlugin from 'eslint-plugin-perfectionist'
import tsPlugin from '@typescript-eslint/eslint-plugin'

// GENERATED BY CURSOR
export default [
  // Config 1: *.ts, *.tsx, *.js, *.jsx (General Sorting)
  {
    files: ['**/*.{ts,tsx,js,jsx}'],
    plugins: {
      perfectionist: perfectionistPlugin,
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      ...perfectionistPlugin.configs['recommended-natural-legacy'].rules, // Apply perfectionist natural sorting
      // Specific overrides for perfectionist
      'perfectionist/sort-interfaces': 'off',
      'perfectionist/sort-intersection-types': 'off',
      'perfectionist/sort-object-types': 'off',
      'perfectionist/sort-classes': 'off', // Handled by @typescript-eslint/member-ordering
      'perfectionist/sort-jsx-props': 'off',
      'perfectionist/sort-union-types': [
        'error',
        {
          type: 'natural',
          order: 'asc',
          ignoreCase: true,
          partitionByNewLine: false,
          partitionByComment: false,
          groups: [
            'conditional',
            'function',
            'import',
            'intersection',
            'keyword',
            'literal',
            'named',
            'object',
            'operator',
            'tuple',
            'union',
            'nullish',
          ],
        },
      ],
      // TypeScript specific member ordering
      '@typescript-eslint/member-ordering': [
        'error',
        {
          default: {
            // No specific default order, rely on class/interface specifics
          },
          interfaces: {
            memberTypes: ['signature', 'constructor', 'field', 'method'],
            order: 'alphabetically',
          },
          classes: {
            // Order members by visibility and type, then alphabetically
            memberTypes: [
              // Static first
              ['public-static-field', 'public-static-method'],
              'private-static-field',
              'private-static-method',
              // Public instance members
              'public-field',
              'public-method',
              // Getters/Setters
              'get',
              'set',
              // Protected instance members
              [
                'protected-field',
                'protected-method',
                'protected-get',
                'protected-set',
              ],
              // Private instance members
              ['private-field', 'private-method'],
              ['private-get', 'private-set'],
            ],
            order: 'alphabetically',
          },
        },
      ],
    },
  },
  // Config 2: *.schema.ts, *.config.ts (Disable sorting)
  {
    files: ['**/*.schema.ts', '**/*.config.ts'],
    rules: {
      // Disable sorting for specific file types where order might matter
      // 'canonical/sort-keys': 'off', // Keep commented if canonical plugin not used
    },
  },
]
