# Anchors don't work with circleci pack
# filters-pr: &filters-pr
#   filters:
#     branches:
#       ignore:
#         - master

jobs:
  - setup-workspace:
      resource_class: large
      max_old_space_size: 6144
      filters:
        branches:
          ignore:
            - master
            - staging
      context:
        # Contains circleci api token for nx orb
        - build
  # - deploy-preview:
  #     # requires:
  #     #   - setup-workspace
  #     filters:
  #       branches:
  #         ignore: /master/
  - lint:
      resource_class: large
      max_old_space_size: 8192
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - setup-workspace
  - build:
      resource_class: large
      max_old_space_size: 4096
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - setup-workspace
  - tsc-check:
      resource_class: large
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - setup-workspace
  - codegen:
      resource_class: medium
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - setup-workspace
  - unit:
      resource_class: large
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - setup-workspace
  - integration:
      resource_class: large
      max_old_space_size: 4096
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - setup-workspace
  - e2e:
      resource_class: large
      # Save ram for docker images
      max_old_space_size: 4096
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - build
  - notify-success:
      resource_class: medium
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - build
        - lint
        - codegen
        - unit
        - integration
        - e2e
