# Anchors don't work with circleci pack
# filters-pr: &filters-pr
#   filters:
#     branches:
#       ignore:
#         - master

jobs:
  - setup-workspace:
      resource_class: large
      max_old_space_size: 6144
      filters:
        branches:
          ignore:
            - master
            - staging
      context:
        # Contains circleci api token for nx orb
        - build
  # - deploy-preview:
  #     # requires:
  #     #   - setup-workspace
  #     filters:
  #       branches:
  #         ignore: /master/
  - lint:
      resource_class: large
      max_old_space_size: 8192
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - setup-workspace
  - build-nx-apps:
      resource_class: large
      max_old_space_size: 4096
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - setup-workspace
  - build-nx-libs:
      resource_class: large
      max_old_space_size: 4096
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - setup-workspace
  - tsc-check:
      resource_class: large
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - setup-workspace
  - codegen:
      resource_class: medium
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - setup-workspace
  - unit:
      resource_class: large
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - setup-workspace
  - integration:
      # 4gb docker + 4gb node = 8gb large
      # 4gb for docker is not enough for high throughput tests
      resource_class: large
      max_old_space_size: 4096
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - setup-workspace
  - e2e:
      resource_class: large
      # Save ram for docker images
      max_old_space_size: 4096
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - build-nx-apps
  - notify-success:
      resource_class: medium
      filters:
        branches:
          ignore:
            - master
            - staging
      requires:
        - lint
        - codegen
        - unit
        - integration
        - build-nx-libs
        - build-nx-apps
        - tsc-check
        - e2e
