jobs:
  - setup-workspace:
      resource_class: arm.large
      max_old_space_size: 6144
      filters:
        branches:
          only:
            - master
  # Will increment docker tag in tf cloud
  - hold-deploy:
      # resource_class: medium
      filters:
        branches:
          only:
            - master
      type: approval
      requires:
        - setup-workspace
  # Apply the new tf settings to ci
  - tf-plan:
      name: 'tf-plan-ci'
      stage: ci
      filters:
        branches:
          only:
            - staging
      requires:
        - hold-deploy
  - tf-apply:
      name: 'tf-apply-ci'
      stage: ci
      filters:
        branches:
          only:
            - staging
      requires:
        - tf-plan-ci
  - setup-infra-workspace:
      # resource_class: large
      filters:
        branches:
          only:
            - master
      requires:
        - hold-deploy
  - docker-web:
      # resource_class: large
      filters:
        branches:
          only:
            - master
      context:
        - prod
      requires:
        - setup-infra-workspace
  - docker-api:
      # resource_class: large
      filters:
        branches:
          only:
            - master
      context:
        - prod
      requires:
        - setup-infra-workspace
  - docker-sites:
      # resource_class: large
      filters:
        branches:
          only:
            - master
      context:
        - prod
      requires:
        - setup-infra-workspace
  - docker-landing:
      # resource_class: large
      filters:
        branches:
          only:
            - master
      context:
        - prod
      requires:
        - setup-infra-workspace
  - tf-plan:
      filters:
        branches:
          only:
            - master
      stage: prod
      requires:
        - docker-web
        - docker-api
        - docker-sites
        - docker-landing
  - hold-apply:
      filters:
        branches:
          only:
            - master
      type: approval
      requires:
        - tf-plan
  - tf-apply:
      filters:
        branches:
          only:
            - master
      stage: prod
      requires:
        - hold-apply
