jobs:
  - setup-workspace:
      resource_class: large
      max_old_space_size: 6144
      filters:
        branches:
          only:
            - master
  - hold-deploy:
      # resource_class: medium
      filters:
        branches:
          only:
            - master
      type: approval
      requires:
        - setup-workspace
  - setup-infra-workspace:
      # resource_class: large
      filters:
        branches:
          only:
            - master
      requires:
        - hold-deploy
  - docker-web:
      # resource_class: large
      filters:
        branches:
          only:
            - master
      context:
        - prod
      requires:
        - setup-infra-workspace
  - docker-api:
      # resource_class: large
      filters:
        branches:
          only:
            - master
      context:
        - prod
      requires:
        - setup-infra-workspace
  - docker-sites:
      # resource_class: large
      filters:
        branches:
          only:
            - master
      context:
        - prod
      requires:
        - setup-infra-workspace
  - docker-landing:
      # resource_class: large
      filters:
        branches:
          only:
            - master
      context:
        - prod
      requires:
        - setup-infra-workspace
  - plan:
      filters:
        branches:
          only:
            - master
      requires:
        - docker-web
        - docker-api
        - docker-sites
        - docker-landing
  - hold-apply:
      filters:
        branches:
          only:
            - master
      type: approval
      requires:
        - plan
  - apply:
      filters:
        branches:
          only:
            - master
      requires:
        - hold-apply
