jobs:
  - setup-workspace:
      filters:
        branches:
          only:
            - master
  - setup-infra-workspace:
      filters:
        branches:
          only:
            - master
      requires:
        - setup-workspace
  - plan:
      filters:
        branches:
          only:
            - master
      requires:
        - setup-infra-workspace
  - hold-apply:
      filters:
        branches:
          only:
            - master
      type: approval
      requires:
        - plan
  - apply:
      filters:
        branches:
          only:
            - master
      requires:
        - hold-apply
