# This runs on staging branch and version tags
jobs:
  - flux-reconcile:
      filters:
        branches:
          only:
            - staging
        tags:
          only: /^([0-9]+\.[0-9]+\.[0-9]+|latest)$/
      context:
        - prod
