# This runs on staging only for testing
jobs:
  # - setup-workspace:
  #     resource_class: large
  #     max_old_space_size: 6144
  #     filters:
  #       branches:
  #         only:
  #           - staging
  - setup-infra-workspace:
      filters:
        branches:
          only:
            - staging
            - feat/3292-production-urls
  - tf-plan:
      name: 'tf-plan-ci'
      filters:
        branches:
          only:
            - staging
            - feat/3292-production-urls
      stage: ci
      requires:
        - setup-infra-workspace
  - tf-apply:
      name: 'tf-apply-ci'
      filters:
        branches:
          only:
            - staging
            - feat/3292-production-urls
      stage: ci
      requires:
        - tf-plan-ci
  # - packer-image:
  #     context:
  #       - prod
  #     filters:
  #       branches:
  #         only:
  #           - staging
  #     requires:
  #       - setup-infra-workspace
  - docker-web:
      filters:
        branches:
          only:
            - staging
            - feat/3292-production-urls
      context:
        - prod
      requires:
        - tf-apply-ci
  - docker-api:
      filters:
        branches:
          only:
            - staging
            - feat/3292-production-urls
      context:
        - prod
      requires:
        - tf-apply-ci
  - docker-sites:
      filters:
        branches:
          only:
            - staging
            - feat/3292-production-urls
      context:
        - prod
      requires:
        - tf-apply-ci
  - docker-landing:
      filters:
        branches:
          only:
            - staging
            - feat/3292-production-urls
      context:
        - prod
      requires:
        - setup-infra-workspace
  - tf-plan:
      filters:
        branches:
          only:
            - staging
            - feat/3292-production-urls
      stage: prod
      requires:
        - docker-web
        - docker-api
        - docker-sites
        - docker-landing
  - hold-apply:
      filters:
        branches:
          only:
            - staging
            - feat/3292-production-urls
      type: approval
      requires:
        - tf-plan
  - tf-apply:
      filters:
        branches:
          only:
            - staging
            - feat/3292-production-urls
      stage: prod
      requires:
        - hold-apply
