# This runs on staging branch and version tags
jobs:
  # - setup-workspace:
  #     resource_class: large
  #     max_old_space_size: 6144
  #     filters:
  #       branches:
  #         only:
  #           - staging
  #       tags:
  #         only: /^([0-9]+\.[0-9]+\.[0-9]+|latest)$/
  - setup-infra-workspace:
      filters:
        branches:
          only:
            - staging
        tags:
          only: /^([0-9]+\.[0-9]+\.[0-9]+|latest)$/
  # - tf-plan:
  #     name: 'tf-plan-ci'
  #     filters:
  #       branches:
  #         only:
  #           - staging
  #       tags:
  #         only: /^([0-9]+\.[0-9]+\.[0-9]+|latest)$/
  #     stage: ci
  #     requires:
  #       - setup-infra-workspace
  # - tf-apply:
  #     name: 'tf-apply-ci'
  #     filters:
  #       branches:
  #         only:
  #           - staging
  #       tags:
  #         only: /^([0-9]+\.[0-9]+\.[0-9]+|latest)$/
  #     stage: ci
  #     requires:
  #       - tf-plan-ci
  # - packer-image:
  #     context:
  #       - prod
  #     filters:
  #       branches:
  #         only:
  #           - staging
  #     requires:
  #       - setup-infra-workspace
  - docker-web:
      filters:
        branches:
          only:
            - staging
        tags:
          only: /^([0-9]+\.[0-9]+\.[0-9]+|latest)$/
      context:
        - prod
      requires:
        - setup-infra-workspace
  - docker-api:
      filters:
        branches:
          only:
            - staging
        tags:
          only: /^([0-9]+\.[0-9]+\.[0-9]+|latest)$/
      context:
        - prod
      requires:
        - setup-infra-workspace
  - docker-sites:
      filters:
        branches:
          only:
            - staging
        tags:
          only: /^([0-9]+\.[0-9]+\.[0-9]+|latest)$/
      context:
        - prod
      requires:
        - setup-infra-workspace
  - docker-landing:
      filters:
        branches:
          only:
            - staging
        tags:
          only: /^([0-9]+\.[0-9]+\.[0-9]+|latest)$/
      context:
        - prod
      requires:
        - setup-infra-workspace
  # - tf-plan:
  #     filters:
  #       branches:
  #         only:
  #           - staging
  #       tags:
  #         only: /^([0-9]+\.[0-9]+\.[0-9]+|latest)$/
  #     stage: prod
  #     requires:
  #       - docker-web
  #       - docker-api
  #       - docker-sites
  #       - docker-landing
  # - hold-apply:
  #     filters:
  #       branches:
  #         only:
  #           - staging
  #       tags:
  #         only: /^([0-9]+\.[0-9]+\.[0-9]+|latest)$/
  #     type: approval
  #     requires:
  #       - tf-plan
  # - tf-apply:
  #     filters:
  #       branches:
  #         only:
  #           - staging
  #       tags:
  #         only: /^([0-9]+\.[0-9]+\.[0-9]+|latest)$/
  #     stage: prod
  #     requires:
  #       - hold-apply
