# This runs on version tags only (no branches)
jobs:
  - setup-infra-workspace:
      filters:
        tags:
          only: /^[0-9]+\.[0-9]+\.[0-9]+$/
  - tf-plan:
      name: 'tf-plan-ci'
      filters:
        tags:
          only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      stage: ci
      requires:
        - setup-infra-workspace
  - tf-apply:
      name: 'tf-apply-ci'
      filters:
        tags:
          only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      stage: ci
      requires:
        - tf-plan-ci
  - docker-web:
      filters:
        tags:
          only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      context:
        - prod
      requires:
        - tf-apply-ci
  - docker-api:
      filters:
        tags:
          only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      context:
        - prod
      requires:
        - tf-apply-ci
  - docker-sites:
      filters:
        tags:
          only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      context:
        - prod
      requires:
        - tf-apply-ci
  - docker-landing:
      filters:
        tags:
          only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      context:
        - prod
      requires:
        - setup-infra-workspace
  - tf-plan:
      filters:
        tags:
          only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      stage: prod
      requires:
        - docker-web
        - docker-api
        - docker-sites
        - docker-landing
  - hold-apply:
      filters:
        tags:
          only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      type: approval
      requires:
        - tf-plan
  - tf-apply:
      filters:
        tags:
          only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      stage: prod
      requires:
        - hold-apply
