# This runs on staging only for testing
jobs:
  - setup-workspace:
      resource_class: large
      max_old_space_size: 6144
      filters:
        branches:
          only:
            - staging
  - setup-infra-workspace:
      filters:
        branches:
          only:
            - staging
      requires:
        - setup-workspace
  # - packer-image:
  #     context:
  #       - prod
  #     filters:
  #       branches:
  #         only:
  #           - staging
  #     requires:
  #       - setup-infra-workspace
  - docker-web:
      filters:
        branches:
          only:
            - staging
      context:
        - prod
      requires:
        - setup-infra-workspace
  - docker-api:
      filters:
        branches:
          only:
            - staging
      context:
        - prod
      requires:
        - setup-infra-workspace
  - docker-sites:
      filters:
        branches:
          only:
            - staging
      context:
        - prod
      requires:
        - setup-infra-workspace
  - docker-landing:
      filters:
        branches:
          only:
            - staging
      context:
        - prod
      requires:
        - setup-infra-workspace
  - plan:
      filters:
        branches:
          only:
            - staging
      requires:
        - docker-web
        - docker-api
        - docker-sites
        - docker-landing
  - hold-apply:
      filters:
        branches:
          only:
            - staging
      type: approval
      requires:
        - plan
  - apply:
      filters:
        branches:
          only:
            - staging
      requires:
        - hold-apply
