#
# `--env-file`, a flag for docker-compose, is used for variable substitution
#
# `env_file` is used to find env to inject into docker container at runtime
#
# https://docs.docker.com/compose/environment-variables/
#
# When you use a bind mount, as in your example, Docker doesn't create a named volume. Instead, it directly maps the file or directory from your host machine into the container. In this case, ./prometheus.yaml from your local machine is being mounted to /etc/prometheus/prometheus.yml within the container.
#
version: '3.8'
name: 'codelab'
services:
  api:
    image: registry.digitalocean.com/codelabapp/api:0.2.0
    restart: unless-stopped
    ports:
      - '4002:4000'

  web:
    image: registry.digitalocean.com/codelabapp/web:0.2.0
    restart: unless-stopped
    ports:
      - '3002:3000'

  landing:
    image: registry.digitalocean.com/codelabapp/landing:0.2.0
    restart: unless-stopped
    ports:
      - '3000:3000'
