#
# `--env-file`, a flag for docker-compose, is used for variable substitution
#
# `env_file` is used to find env to inject into container at runtime
#
version: '3.8'
services:
  platform:
    build:
      context: ../
      dockerfile: ${PWD}/.docker/platform.Dockerfile
    # image: codelabai/codelab:${DOCKER_TAG_VERSION}
    # This is used after image has been built
    env_file:
      - ../.env
    environment:
      - NODE_ENV=development
