#
# `--env-file`, a flag for docker-compose, is used for variable substitution
#
# `env_file` is used to find env to inject into docker container at runtime
#
# https://docs.docker.com/compose/environment-variables/
#
version: '3.8'
services:
  neo4j:
    container_name: codelab-neo4j
    image: neo4j:latest
    volumes:
      - codelab-neo4j:/data
      - codelab-neo4j:/plugins
      - codelab-neo4j:/import
      - codelab-neo4j:/logs
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      #   - NEO4J_apoc_export_file_enabled=true
      #   - NEO4J_apoc_import_file_enabled=true
      #   - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      #   - NEO4J_dbms_memory_heap_initial__size=512m
      #   - NEO4J_dbms_memory_heap_max__size=2G
      #   - NEO4J_apoc_uuid_enabled=true
      #   - NEO4J_dbms_default__listen__address=0.0.0.0
      #   - NEO4J_dbms_allow__upgrade=true
      #   - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/test
    # networks: ["codelab-neo4j"]
    restart: unless-stopped
  zero:
    container_name: codelab-dgraph-zero
    image: dgraph/dgraph:v21.03.1
    volumes:
      - dgraph:/dgraph
    restart: on-failure
    command: dgraph zero --my=zero:5080

  alpha:
    container_name: codelab-dgraph-alpha
    depends_on:
      - zero
    image: dgraph/dgraph:v21.03.1
    volumes:
      - dgraph:/dgraph
    ports:
      - 8080:8080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=0.0.0.0/0 --limit "mutations=strict"

  zero-test:
    container_name: codelab-dgraph-zero-test
    image: dgraph/dgraph:v21.03.1
    volumes:
      - dgraph-test:/dgraph
    restart: on-failure
    command: dgraph zero --my=zero-test:5080

  alpha-test:
    container_name: codelab-dgraph-alpha-test
    depends_on:
      - zero-test
    image: dgraph/dgraph:v21.03.1
    volumes:
      - dgraph-test:/dgraph
    ports:
      - 8081:8080
    restart: on-failure
    command: dgraph alpha --my=alpha-test:7080 --zero=zero-test:5080 --security whitelist=0.0.0.0/0 --limit "mutations=strict"

volumes:
  dgraph:
    name: codelab-dgraph-volume
  dgraph-test:
    name: codelab-dgraph-test-volume
  codelab-neo4j:
    name: codelab-neo4j-volume
