import type { PackageJson } from 'type-fest'

/**
 * Updates the exports field in a package.json object.
 *
 * @param packageJson - The package.json object to modify.
 * @param relativeExports - The exports map generated by getRelativeExports.
 */
export const setPackageJsonExports = (
  packageJson: PackageJson,
  relativeExports: Record<
    string,
    { default: string; import: string; types: string }
  >,
): void => {
  const exports = {
    '.': {
      default: './src/index.ts',
      import: './src/index.ts',
      types: './src/index.ts',
    },
  }

  packageJson.exports = { ...exports, ...relativeExports }

  console.log('Updated package.json exports field.')
}
