import type { ProjectConfiguration, Tree } from '@nx/devkit'
import type { PackageJson } from 'type-fest'

import { joinPathFragments, readJson, writeJson } from '@nx/devkit'

import { getProjectImports } from '../imports/project-imports'
import {
  getPackageNameFromOldAlias,
  getPackageNameFromProjectName,
} from '../path-alias/path-alias'
import { getRelativeExports } from './exports/relative-exports'
import { getBaseImportPaths } from './paths'
import { setDevDependencies } from './setter/package-dev-dependencies'
import { setPackageJsonExports } from './setter/package-exports'
import { setPackageJsonName } from './setter/package-name'

/**
 * Creates package.json files for non-buildable projects, including dependency analysis
 */
export const createNonbuildablePackageJson = (
  tree: Tree,
  projectConfig: ProjectConfiguration,
) => {
  const projectName = projectConfig.name

  console.log(
    `Creating/Updating package.json for ${projectName} (non-buildable library)`,
  )

  if (!projectName) {
    throw new Error('Project name is required')
  }

  const packageJson: PackageJson = {}
  const packageName = getPackageNameFromProjectName(projectName)

  setPackageJsonName(packageJson, projectName)

  // Get transformed imports
  console.log('Getting project imports')

  const allImports = getProjectImports(tree, projectConfig).map((importPath) =>
    getPackageNameFromOldAlias(importPath),
  )

  console.log(
    `Found ${allImports.length} potential @codelab imports in ${projectName}`,
  )

  const baseImportPaths = getBaseImportPaths(allImports)

  console.log(
    `Found ${baseImportPaths.length} unique base @codelab dependencies to add.`,
  )

  // Save import data
  // saveImportData(tree, projectConfig.root, allImports, baseImportPaths)

  const relativeExports = getRelativeExports(
    allImports,
    baseImportPaths,
    packageName,
  )

  console.log(
    'Generated Exports Map:',
    JSON.stringify(relativeExports, null, 2),
  )

  setPackageJsonExports(packageJson, relativeExports)
  setDevDependencies(packageJson, baseImportPaths)

  writeToPackageJson(tree, projectConfig.root, packageJson)
}

/**
 * Saves the collected import data to a data.json file within the project root.
 * GENERATED BY CURSOR
 */
const saveImportData = (
  tree: Tree,
  projectRoot: string,
  allImports: Array<string>,
  baseImportPaths: Array<string>,
) => {
  const dataPath = joinPathFragments(projectRoot, 'data.json')

  const data = {
    allImports,
    baseImportPaths,
  }

  console.log(`Writing import data to ${dataPath}`)
  writeJson(tree, dataPath, data)
}

/**
 * Writes the package.json object to the specified path within the project root.
 */
const writeToPackageJson = (
  tree: Tree,
  projectRoot: string,
  packageJson: PackageJson,
) => {
  const packageJsonPath = joinPathFragments(projectRoot, 'package.json')

  console.log(`Writing updated package.json to ${packageJsonPath}`)
  writeJson(tree, packageJsonPath, packageJson)
}
