import type { ProjectConfiguration, Tree } from '@nx/devkit'

import { joinPathFragments, readJson, writeJson } from '@nx/devkit'

/**
 * Updates the package.json for a Vite library project.
 * GENERATED BY CURSOR
 */
export const updatePackageJsonForVite = (
  tree: Tree,
  projectConfig: ProjectConfiguration,
) => {
  const packageJsonPath = joinPathFragments(projectConfig.root, 'package.json')

  if (!tree.exists(packageJsonPath)) {
    console.warn(
      `Package.json not found at ${packageJsonPath}, skipping update.`,
    )

    return
  }

  const packageJson = readJson(tree, packageJsonPath)

  // Add or update the required fields
  packageJson.type = 'module'
  delete packageJson.main
  delete packageJson.module
  delete packageJson.types

  // Write the updated package.json back to the file
  writeJson(tree, packageJsonPath, packageJson)
  console.log(`Updated package.json at: ${packageJsonPath}`)

  // Return package json for potential use
  return packageJson
}
