#!/bin/bash

echo 'Starting entrypoint...'

# Start Neo4j normally in the background using the official entrypoint
# that comes with the image
/startup/docker-entrypoint.sh neo4j &

# Reuse the logic from the health check to determine when Neo4j is ready
until wget -O /dev/null -q http://localhost:7474; do
  sleep 1
done

echo 'Neo4j ready...'

# Neo4j subscriptions in @neo4j/graphql@6 requires an enterprise image with CDC enabled
# https://neo4j.com/docs/cdc/current/get-started/self-managed/#_modify_a_databases_cdc_mode
cypher-shell -a localhost:7687 -u neo4j -p password 'ALTER DATABASE neo4j SET OPTION txLogEnrichment "DIFF"'

cypher-shell -a localhost:7687 -u neo4j -p password 'SHOW DATABASES YIELD name, options'

# Contraints are no longer autogenerated in v6
echo 'Cypher-shell adding constraints...'

cypher-shell -a localhost:7687 -u neo4j -p password -f /scripts/constraints.cypher

# Keep container running in the foreground
tail -f /dev/null
