/* eslint-disable @typescript-eslint/ban-types */
import type { IPropData } from '@codelab/shared-abstract-core'

import { isValidElement } from 'react'
import {
  isArray,
  isFunction,
  isObjectType,
  isPlainObject,
  pickBy,
} from 'remeda'

/**
 * GENERATED BY CURSOR
 *
 * Safely stringifies props object for display purposes, handling React elements, circular references, and functions.
 *
 * @param props - The props object to stringify
 * @param maskFunctions - When true, replaces function values with the string 'function' in the output JSON.
 * This prevents functions from being completely omitted (default JSON.stringify behavior) while indicating
 * a function existed at that property. If false, functions follow the default JSON.stringify behavior and are omitted.
 * @returns A JSON string representation of the props
 */
export const propSafeStringify = (props: IPropData, maskFunctions = true) => {
  const obj = pickBy(props, (value, key) => !key.startsWith('_'))
  const cache = new WeakMap<object, boolean>()

  const replacer = (key: string, value: object) => {
    // handle ReactNodeType
    if (isValidElement(value)) {
      return 'React element'
    }

    if (isObjectType(value)) {
      if (!isArray(value) && !isPlainObject(value)) {
        return `${value.constructor.name} instance`
      }

      // Duplicate reference found, discard key
      if (cache.get(value)) {
        return
      }

      // Store value in our collection
      cache.set(value, true)
    }

    if (maskFunctions && isFunction(value)) {
      return 'function'
    }

    return value
  }

  const result = JSON.stringify(obj, replacer, 4)

  return result
}
