#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn cross-env TIMING=1 lint-staged --verbose

yarn lint:graphql

# Always sync metadata
npx hasura metadata export --project=hasura --envfile=./../.env

./scripts/lint/git.sh