#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn cli tasks build --stage test
yarn cli tasks unit --stage test
yarn cli tasks int --stage test
nx e2e platform-e2e --watch false --exit true

./scripts/git/branch-name-check.sh
