version: '3.8'
services:
  api:
    image: registry.digitalocean.com/codelabapp/api:${docker_tag_version}
    container_name: codelab-api
    restart: unless-stopped
    ports:
      - '${local_port}:${next_public_api_port}'
    environment:
      - AUTH0_M2M_CLIENT_ID=${auth0_m2m_client_id}
      - AUTH0_M2M_CLIENT_SECRET=${auth0_m2m_client_secret}
      - AUTH0_DOMAIN=${auth0_domain}
      - NEO4J_URI=${neo4j_uri}
      - NEO4J_USER=${neo4j_user}
      - NEO4J_PASSWORD=${neo4j_password}
  coredns:
    image: coredns/coredns:1.11.1
    volumes:
      - ./Corefile:/etc/coredns/Corefile
    ports:
      - '53:53/udp'
      - '53:53/tcp'
    restart: unless-stopped
