---
# Reusable cleanup tasks for service images
# This should be included at the end of each service playbook
# to ensure proper machine-id cleanup and deployment readiness

# Critical: Clean machine-id for proper first boot detection
# Use cloud-init's proper cleanup method which sets machine-id to "uninitialized\n"
# This ensures systemd's ConditionFirstBoot=yes works correctly
- name: Copy machine-id cleanup script
  copy:
    src: service-cleanup.sh
    dest: /tmp/service-cleanup.sh
    mode: '0755'

- name: Clean machine-id and cloud-init state for first boot
  command: /tmp/service-cleanup.sh

- name: Remove cleanup script
  file:
    path: /tmp/service-cleanup.sh
    state: absent

# Remove SSH host keys (will be regenerated on first boot)
# This ensures each instance has unique SSH keys
- name: Remove SSH host keys
  shell: rm -f /etc/ssh/ssh_host_*
  failed_when: false

# Trim filesystem to minimize snapshot size
# Reduces the final image size by releasing unused blocks
- name: Trim filesystem
  command: fstrim -av
  failed_when: false
