on:
  push:
    branches:
      - master
# jobs:
#   deploy-web:
#     runs-on: ubuntu-latest
#     steps:
#       - name: web deployment
#         uses: digitalocean/app_action@v1.1.6
#         with:
#           app_name: web
#           token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#   deploy-api:
#     runs-on: ubuntu-latest
#     steps:
#       - name: api deployment
#         uses: digitalocean/app_action@v1.1.6
#         with:
#           app_name: api
#           token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#   deploy-websites:
#     runs-on: ubuntu-latest
#     steps:
#       - name: websites deployment
#         uses: digitalocean/app_action@v1.1.6
#         with:
#           app_name: websites
#           token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
